import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Check, Copy, Flower2, Gift, Heart, MapPin, Menu, MessageCircle, Minus, Plus, Sparkles, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Countdown } from "@/components/wedding/countdown";
import { asPix, asTheme, asVenue, buildPixPayload, resolveWeddingPhoto, safeGoogleMapsUrl, weddingThemeStyle, type Venue, type Wedding, type WeddingSection } from "@/lib/wedding";
import type { Tables } from "@/integrations/supabase/types";

type GiftRow=Tables<"gifts"> & {display_url?:string};
const labels:Record<WeddingSection,string>={story:"Nós",ceremony:"Cerimônia",reception:"Recepção",rsvp:"Confirmar presença",gifts:"Presentes",contact:"Contato"};
export const Route=createFileRoute("/casamento/$slug")({head:({params})=>({meta:[{title:`Casamento — ${params.slug}`},{name:"description",content:"Celebre conosco e confirme sua presença."},{property:"og:title",content:"Nosso casamento"},{property:"og:description",content:"Celebre conosco e confirme sua presença."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:WeddingPage});

function WeddingPage(){
 const {slug}=Route.useParams(); const [wedding,setWedding]=useState<Wedding|null>(null); const [cover,setCover]=useState(""); const [gifts,setGifts]=useState<GiftRow[]>([]); const [menu,setMenu]=useState(false); const [gift,setGift]=useState<GiftRow|null>(null); const [venuePhotos,setVenuePhotos]=useState<Record<string,string[]>>({});
 const [form,setForm]=useState({name:"",attending:null as boolean|null,guests:0,children:0,helpers:0,guestNames:[] as string[],childNames:[] as string[],helperNames:[] as string[],whatsapp:"",message:""}); const [status,setStatus]=useState(""); const [rsvpSuccess,setRsvpSuccess]=useState(false);
 const [giftNote,setGiftNote]=useState({senderName:"",message:""}); const [giftStatus,setGiftStatus]=useState(""); const [sendingGift,setSendingGift]=useState(false);
 useEffect(()=>{supabase.from("weddings").select("*").eq("slug",slug).eq("is_published",true).maybeSingle().then(async({data})=>{if(!data)return;const parsed={...data,ceremony:asVenue(data.ceremony),reception:asVenue(data.reception),pix:asPix(data.pix),theme:asTheme(data.theme)} as unknown as Wedding;setWedding(parsed);setCover(await resolveWeddingPhoto(parsed.cover_photo));const [ceremony,reception]=await Promise.all([Promise.all(parsed.ceremony.fotos.map(resolveWeddingPhoto)),Promise.all(parsed.reception.fotos.map(resolveWeddingPhoto))]);setVenuePhotos({ceremony,reception});const g=await supabase.from("gifts").select("*").eq("wedding_id",data.id).order("created_at");setGifts(await Promise.all((g.data||[]).map(async item=>({...item,display_url:item.image_url?await resolveWeddingPhoto(item.image_url):""}))));});},[slug]);
 const pix=useMemo(()=>gift&&wedding?.pix.key?buildPixPayload(wedding.pix.key,wedding.pix.name||"PRESENTE CASAMENTO",wedding.pix.city||"BRASIL",Number(gift.price),gift.id.slice(0,20)):"",[gift,wedding]);
 async function submit(e:React.FormEvent){e.preventDefault();const name=form.name.trim();const message=form.message.trim();if(!wedding||name.length<2||name.length>120||form.attending===null){setStatus("Preencha seu nome e informe se poderá comparecer.");return;}if(message.length>600){setStatus("O recado pode ter no máximo 600 caracteres.");return;}const {error}=await supabase.from("rsvps").insert({wedding_id:wedding.id,owner_id:wedding.owner_id,name,attending:form.attending,guest_count:form.attending?form.guests:0,guest_names:form.attending?form.guestNames:[],children_count:form.attending?form.children:0,child_names:form.attending?form.childNames:[],helpers_count:form.attending?form.helpers:0,helper_names:form.attending?form.helperNames:[],whatsapp:form.whatsapp,message:message||null});if(!error){setForm({...form,name:"",whatsapp:"",message:"",guestNames:[],childNames:[],helperNames:[]});if(form.attending){setRsvpSuccess(true);}else{setStatus("Obrigado por avisar. Vamos sentir sua falta!");}}else{setStatus("Não foi possível enviar. Tente novamente.");}}
 async function sendGiftMessage(){const senderName=giftNote.senderName.trim();const message=giftNote.message.trim();if(!gift||!wedding||senderName.length<2||senderName.length>120){setGiftStatus("Informe seu nome para os noivos saberem quem enviou o presente.");return;}if(message.length>600){setGiftStatus("O recado pode ter no máximo 600 caracteres.");return;}setSendingGift(true);setGiftStatus("");const {error}=await supabase.from("gift_messages").insert({gift_id:gift.id,wedding_id:wedding.id,owner_id:wedding.owner_id,sender_name:senderName,message:message||null});setSendingGift(false);if(error){setGiftStatus("Este presente pode já ter sido escolhido. Atualize a página e tente outro.");return;}setGifts(current=>current.map(item=>item.id===gift.id?{...item,is_given:true}:item));setGiftStatus("Presente registrado. Os noivos receberão seu carinho!");setGiftNote({senderName:"",message:""});}
 if(!wedding)return <main className="flex min-h-screen items-center justify-center"><p>Este casamento não está disponível.</p></main>;
 const visible=wedding.theme.sections.filter(item=>!wedding.theme.hidden.includes(item));
 const content:Record<WeddingSection,ReactNode>={
  story:<section id="story" className="px-5 py-24"><div className={`mx-auto grid max-w-5xl gap-10 ${wedding.theme.template==="editorial"?"md:grid-cols-[1fr_1.4fr]":"md:grid-cols-[.7fr_1fr]"}`}><Title eyebrow="Um pouco sobre nós">Nossa história</Title><p className="text-lg leading-8 text-muted-foreground">{wedding.story}</p></div></section>,
  ceremony:<VenueSection id="ceremony" eyebrow="Onde tudo começa" title="Cerimônia" value={wedding.ceremony} photos={venuePhotos["ceremony"]||[]} template={wedding.theme.template}/>,
  reception:<VenueSection id="reception" eyebrow="A celebração" title="Recepção" value={wedding.reception} photos={venuePhotos["reception"]||[]} template={wedding.theme.template}/>,
   rsvp:<section id="rsvp" className="px-5 py-24"><div className="mx-auto max-w-3xl"><div className="text-center"><Title eyebrow="Contamos com você">Confirmar presença</Title></div><form onSubmit={submit} className="mt-12 border border-border bg-background p-6 shadow-xl md:p-10"><Label>Seu nome completo</Label><Input className="mt-2 h-12" maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Label className="mt-6 block">Você vai comparecer?</Label><div className="mt-3 grid grid-cols-2 gap-3"><Button type="button" variant={form.attending===true?"default":"outline"} onClick={()=>setForm({...form,attending:true})}>Sim, estarei lá</Button><Button type="button" variant={form.attending===false?"default":"outline"} onClick={()=>setForm({...form,attending:false})}>Não poderei ir</Button></div>{form.attending&&<div className="mt-6 space-y-6"><Counter label="Acompanhantes adultos" value={form.guests} onChange={n=>setForm({...form,guests:n,guestNames:Array(n).fill("").map((_,i)=>form.guestNames[i]||"")})}/><Names count={form.guests} label="Nome do acompanhante" values={form.guestNames} onChange={v=>setForm({...form,guestNames:v})}/><Counter label="Crianças" value={form.children} onChange={n=>setForm({...form,children:n,childNames:Array(n).fill("").map((_,i)=>form.childNames[i]||"")})}/><Names count={form.children} label="Nome da criança" values={form.childNames} onChange={v=>setForm({...form,childNames:v})}/><Counter label="Ajuda (babá, motorista ou apoio)" value={form.helpers} onChange={n=>setForm({...form,helpers:n,helperNames:Array(n).fill("").map((_,i)=>form.helperNames[i]||"")})}/><Names count={form.helpers} label="Nome" values={form.helperNames} onChange={v=>setForm({...form,helperNames:v})}/></div>}<Label className="mt-6 block">Seu WhatsApp</Label><Input className="mt-2 h-12" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})} placeholder="(31) 99999-9999"/><Label className="mt-6 block">Deixe um recado para os noivos <span className="font-normal text-muted-foreground">(opcional)</span></Label><Textarea className="mt-2 min-h-28" maxLength={600} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Escreva uma mensagem carinhosa…"/><p className="mt-1 text-right text-xs text-muted-foreground">{form.message.length}/600</p><Button type="submit" size="lg" className="mt-7 w-full"><Check/>Enviar confirmação</Button>{status&&<p className="mt-4 text-center text-sm">{status}</p>}</form></div></section>,
  gifts:<section id="gifts" className="bg-primary px-5 py-24 text-primary-foreground"><div className="mx-auto max-w-6xl"><div className="text-center"><Title eyebrow="Com carinho">Lista de presentes</Title><p className="mt-4 text-primary-foreground/75">Se preferir presentear por aqui, é só escolher um item.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{gifts.map(g=><article className="bg-background text-foreground" key={g.id}>{g.display_url?<img src={g.display_url} alt={g.name} className="aspect-[4/3] w-full object-cover" loading="lazy"/>:<div className="flex aspect-[4/3] items-center justify-center bg-secondary"><ThemeIcon style={wedding.theme.icons}/></div>}<div className="p-5"><h3 className="text-2xl">{g.name}</h3><p className="mt-1 text-muted-foreground">R$ {Number(g.price).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p><Button className="mt-5 w-full" disabled={g.is_given} onClick={()=>setGift(g)}>{g.is_given?"Já presenteado":"Presentear via Pix"}</Button></div></article>)}</div></div></section>,
  contact:<section id="contact" className="px-5 py-20 text-center"><Title>Fale conosco</Title><p className="mt-3 text-muted-foreground">Qualquer dúvida, é só chamar no WhatsApp.</p>{wedding.whatsapp&&<Button asChild className="mt-6"><a target="_blank" rel="noreferrer" href={`https://wa.me/${wedding.whatsapp}?text=${encodeURIComponent(`Olá! Vi o site do casamento de ${wedding.couple_names}`)}`}><MessageCircle/>Chamar no WhatsApp</a></Button>}</section>
 };
 return <main style={weddingThemeStyle(wedding.theme)} className={`wedding-theme wedding-palette-${wedding.theme.palette} wedding-font-${wedding.theme.font} bg-background text-foreground`}><nav className="fixed inset-x-0 top-0 z-30 border-b border-background/20 bg-foreground/60 text-primary-foreground backdrop-blur-lg"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href="#inicio" className="font-serif text-2xl">{wedding.couple_names}</a><Button size="icon" variant="ghost" aria-label="Abrir menu" className="md:hidden" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button><div className={`${menu?"flex":"hidden"} absolute left-0 right-0 top-full flex-col bg-foreground p-5 md:static md:flex md:flex-row md:bg-transparent md:p-0`}>{visible.map(section=><a className="px-3 py-2 text-xs uppercase" href={`#${section}`} key={section} onClick={()=>setMenu(false)}>{labels[section]}</a>)}</div></div></nav>
 <section id="inicio" className={`relative flex min-h-[92vh] overflow-hidden px-5 pb-14 pt-28 ${wedding.theme.heroAlign==="center"?"items-end justify-center text-center":"items-end justify-start text-left md:px-12"}`}>{cover&&<img src={cover} alt={`Foto de ${wedding.couple_names}`} className="absolute inset-0 h-full w-full object-cover"/>}<div className="absolute inset-0 bg-gradient-to-t from-foreground/85 via-foreground/25 to-transparent"/><div className={`relative z-10 animate-rise text-primary-foreground ${wedding.theme.heroAlign==="left"?"max-w-4xl":""}`}><p className="mb-3 text-xs uppercase">Nós vamos nos casar</p><h1 className="text-6xl leading-none md:text-8xl">{wedding.couple_names}</h1><p className="my-7 text-sm uppercase">{wedding.date_text}</p><Countdown date={wedding.wedding_at}/><Button variant="hero" asChild className="mt-8"><a href="#rsvp">Confirmar presença</a></Button></div></section>
 {visible.map(section=><div key={section}>{content[section]}</div>)}
 <footer className="border-t border-border px-5 py-8 text-center text-sm text-muted-foreground">Feito com carinho para {wedding.couple_names} · {wedding.date_text}</footer>
  <Dialog open={Boolean(gift)} onOpenChange={o=>{if(!o){setGift(null);setGiftStatus("");setGiftNote({senderName:"",message:""});}}}><DialogContent><DialogHeader><DialogTitle>{gift?.name}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Copie a chave Pix abaixo e realize o pagamento no aplicativo do seu banco.</p>{wedding?.pix.key?<><div className="mt-3 flex items-center gap-2 rounded bg-muted p-3"><span className="flex-1 break-all font-mono text-sm">{wedding.pix.key}</span><Button size="icon" variant="ghost" title="Copiar chave Pix" onClick={()=>navigator.clipboard.writeText(wedding.pix.key)}><Copy className="size-4"/></Button></div>{wedding.pix.name&&<p className="mt-2 text-xs text-muted-foreground">Recebedor: {wedding.pix.name}{wedding.pix.city?` · ${wedding.pix.city}`:""}</p>}</>:<p className="mt-3 text-sm text-muted-foreground">Os noivos ainda não configuraram a chave Pix.</p>}<div className="mt-5 border-t border-border pt-5"><Label>Seu nome</Label><Input className="mt-2" maxLength={120} value={giftNote.senderName} onChange={e=>setGiftNote({...giftNote,senderName:e.target.value})} placeholder="Quem está presenteando?"/><Label className="mt-4 block">Recado para os noivos <span className="font-normal text-muted-foreground">(opcional)</span></Label><Textarea className="mt-2 min-h-24" maxLength={600} value={giftNote.message} onChange={e=>setGiftNote({...giftNote,message:e.target.value})} placeholder="Escreva uma mensagem carinhosa…"/><p className="mt-1 text-right text-xs text-muted-foreground">{giftNote.message.length}/600</p><Button className="mt-4 w-full" onClick={sendGiftMessage} disabled={sendingGift||!wedding?.pix.key}>{sendingGift?"Enviando…":"Já fiz o Pix — enviar recado"}</Button>{giftStatus&&<p className="mt-3 text-center text-sm text-muted-foreground">{giftStatus}</p>}</div></DialogContent></Dialog>
 <Dialog open={rsvpSuccess} onOpenChange={setRsvpSuccess}><DialogContent className="max-w-sm"><div className="flex justify-center mb-4"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-primary/10"><Heart className="size-8 text-primary"/></span></div><DialogHeader><DialogTitle className="text-center text-2xl">Presença confirmada!</DialogTitle></DialogHeader><p className="mt-2 text-center text-muted-foreground">Mal podemos esperar para ver você. Será uma celebração inesquecível! 🎉</p>{!wedding?.theme.hidden.includes("gifts")&&<div className="mt-5 border-t border-border pt-5 text-center"><p className="text-sm font-medium">Gostaria de presentear os noivos?</p><Button asChild variant="outline" className="mt-3 w-full" onClick={()=>setRsvpSuccess(false)}><a href="#gifts"><Gift className="mr-2 size-4"/>Ver lista de presentes</a></Button></div>}<Button className="mt-3 w-full" variant="ghost" onClick={()=>setRsvpSuccess(false)}>Fechar</Button></DialogContent></Dialog></main>;
}
function Title({eyebrow,children}:{eyebrow?:string;children:ReactNode}){return <div>{eyebrow&&<p className="text-xs font-semibold uppercase text-accent">{eyebrow}</p>}<h2 className="mt-3 text-5xl">{children}</h2></div>}
function ThemeIcon({style}:{style:Wedding["theme"]["icons"]}){if(style==="floral")return <Flower2 className="size-14 text-accent"/>;if(style==="classic")return <Sparkles className="size-14 text-accent"/>;return <Gift className="size-14 text-accent"/>}
function VenueSection({id,eyebrow,title,value,photos,template}:{id:string;eyebrow:string;title:string;value:Venue;photos:string[];template:Wedding["theme"]["template"]}){const mapsUrl=safeGoogleMapsUrl(value.maps_url);if(!value.local&&!value.endereco&&!photos.length)return null;return <section id={id} className="bg-secondary/50 px-5 py-20"><div className={`mx-auto grid max-w-6xl gap-8 ${template==="classic"?"text-center":"lg:grid-cols-2"}`}><div className="bg-background p-8"><Title eyebrow={eyebrow}>{title}</Title><h3 className="mt-10 text-2xl">{value.local}</h3><div className="mt-5 space-y-2 text-muted-foreground"><p>{value.data}{value.data&&value.hora?" · ":""}{value.hora}</p>{value.endereco&&<p className={`flex gap-2 ${template==="classic"?"justify-center":""}`}><MapPin className="mt-1 size-4 shrink-0"/>{value.endereco}</p>}</div>{mapsUrl&&<Button asChild variant="outline" className="mt-6"><a href={mapsUrl} target="_blank" rel="noreferrer"><MapPin/>Abrir no Google Maps</a></Button>}</div>{value.endereco&&<iframe title={`Mapa de ${value.local}`} className="min-h-80 w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={`https://www.google.com/maps?q=${encodeURIComponent(value.endereco)}&output=embed`}/>}</div>{photos.length>0&&<div className="mx-auto mt-6 grid max-w-6xl gap-3 sm:grid-cols-2">{photos.map((url,i)=><img key={`${url}-${i}`} src={url} alt={`${value.local} ${i+1}`} loading="lazy" className="aspect-video w-full object-cover"/>)}</div>}</section>}
function Counter({label,value,onChange}:{label:string;value:number;onChange:(n:number)=>void}){return <div className="flex items-center justify-between"><Label>{label}</Label><div className="flex items-center gap-3"><Button type="button" size="icon" variant="outline" onClick={()=>onChange(Math.max(0,value-1))}><Minus/></Button><span className="w-5 text-center">{value}</span><Button type="button" size="icon" variant="outline" onClick={()=>onChange(Math.min(20,value+1))}><Plus/></Button></div></div>}
function Names({count,label,values,onChange}:{count:number;label:string;values:string[];onChange:(v:string[])=>void}){return <div className="space-y-2">{Array.from({length:count},(_,i)=><Input key={i} placeholder={`${label} ${i+1}`} value={values[i]||""} onChange={e=>{const copy=[...values];copy[i]=e.target.value;onChange(copy)}}/>)}</div>}