import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Check, Copy, Gift, MapPin, Menu, MessageCircle, Minus, Plus, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Countdown } from "@/components/wedding/countdown";
import { asPix, asVenue, buildPixPayload, type Wedding } from "@/lib/wedding";
import type { Tables } from "@/integrations/supabase/types";

type GiftRow=Tables<"gifts">;
export const Route=createFileRoute("/casamento/$slug")({head:({params})=>({meta:[{title:`Casamento — ${params.slug}`},{name:"description",content:"Celebre conosco e confirme sua presença."},{property:"og:title",content:"Nosso casamento"},{property:"og:description",content:"Celebre conosco e confirme sua presença."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:WeddingPage});
function WeddingPage(){const {slug}=Route.useParams();const [wedding,setWedding]=useState<Wedding|null>(null);const [gifts,setGifts]=useState<GiftRow[]>([]);const [menu,setMenu]=useState(false);const [gift,setGift]=useState<GiftRow|null>(null);const [form,setForm]=useState({name:"",attending:null as boolean|null,guests:0,children:0,helpers:0,guestNames:[] as string[],childNames:[] as string[],helperNames:[] as string[],whatsapp:""});const [status,setStatus]=useState("");
useEffect(()=>{supabase.from("weddings").select("*").eq("slug",slug).eq("is_published",true).maybeSingle().then(async({data})=>{if(!data)return;setWedding({...data,ceremony:asVenue(data.ceremony),reception:asVenue(data.reception),pix:asPix(data.pix)} as Wedding);const g=await supabase.from("gifts").select("*").eq("wedding_id",data.id).order("created_at");setGifts(g.data||[]);});},[slug]);
const pix=useMemo(()=>gift&&wedding?.pix.key?buildPixPayload(wedding.pix.key,wedding.pix.name||"PRESENTE CASAMENTO",wedding.pix.city||"BRASIL",Number(gift.price),gift.id.slice(0,20)):"",[gift,wedding]);
async function submit(e:React.FormEvent){e.preventDefault();if(!wedding||!form.name.trim()||form.attending===null){setStatus("Preencha seu nome e informe se poderá comparecer.");return;}const {error}=await supabase.from("rsvps").insert({wedding_id:wedding.id,owner_id:wedding.owner_id,name:form.name.trim(),attending:form.attending,guest_count:form.attending?form.guests:0,guest_names:form.attending?form.guestNames:[],children_count:form.attending?form.children:0,child_names:form.attending?form.childNames:[],helpers_count:form.attending?form.helpers:0,helper_names:form.attending?form.helperNames:[],whatsapp:form.whatsapp});setStatus(error?"Não foi possível enviar. Tente novamente.":form.attending?"Presença confirmada! Mal podemos esperar para ver você.":"Obrigado por avisar. Vamos sentir sua falta!");if(!error)setForm({...form,name:"",whatsapp:"",guestNames:[],childNames:[],helperNames:[]});}
if(!wedding)return <main className="flex min-h-screen items-center justify-center"><p>Este casamento não está disponível.</p></main>;const nav=[["historia","Nós"],["cerimonia","Cerimônia"],["recepcao","Recepção"],["confirmar","Confirmar presença"],["presentes","Presentes"]];
return <main className="bg-background"><nav className="fixed inset-x-0 top-0 z-30 border-b border-background/20 bg-foreground/60 text-primary-foreground backdrop-blur-lg"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href="#inicio" className="font-serif text-2xl">{wedding.couple_names}</a><button aria-label="Abrir menu" className="md:hidden" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className={`${menu?"flex":"hidden"} absolute left-0 right-0 top-full flex-col bg-foreground p-5 md:static md:flex md:flex-row md:bg-transparent md:p-0`}>{nav.map(([id,label])=><a className="px-3 py-2 text-xs uppercase" href={`#${id}`} key={id} onClick={()=>setMenu(false)}>{label}</a>)}</div></div></nav>
<section id="inicio" className="relative flex min-h-[92vh] items-end justify-center overflow-hidden px-5 pb-14 pt-28 text-center"><img src={wedding.cover_photo} alt={`Foto de ${wedding.couple_names}`} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-foreground/85 via-foreground/25 to-transparent"/><div className="relative z-10 animate-rise text-primary-foreground"><p className="mb-3 text-xs uppercase">Nós vamos nos casar</p><h1 className="text-6xl leading-none md:text-8xl">{wedding.couple_names}</h1><p className="my-7 text-sm uppercase">{wedding.date_text}</p><Countdown date={wedding.wedding_at}/><Button variant="hero" asChild className="mt-8"><a href="#confirmar">Confirmar presença</a></Button></div></section>
<section id="historia" className="px-5 py-24"><div className="mx-auto grid max-w-5xl gap-10 md:grid-cols-[.7fr_1fr]"><div><p className="text-xs font-semibold uppercase text-accent">Um pouco sobre nós</p><h2 className="mt-3 text-5xl">Nossa história</h2></div><p className="text-lg leading-8 text-muted-foreground">{wedding.story}</p></div></section>
<div className="bg-secondary/50"><VenueSection id="cerimonia" eyebrow="Onde tudo começa" title="Cerimônia" value={wedding.ceremony}/><VenueSection id="recepcao" eyebrow="A celebração" title="Recepção" value={wedding.reception}/></div>
<section id="confirmar" className="px-5 py-24"><div className="mx-auto max-w-3xl"><div className="text-center"><p className="text-xs font-semibold uppercase text-accent">Contamos com você</p><h2 className="mt-3 text-5xl">Confirmar presença</h2></div><form onSubmit={submit} className="mt-12 border border-border bg-background p-6 shadow-xl md:p-10"><Label>Seu nome completo</Label><Input className="mt-2 h-12" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Label className="mt-6 block">Você vai comparecer?</Label><div className="mt-3 grid grid-cols-2 gap-3"><Button type="button" variant={form.attending===true?"default":"outline"} onClick={()=>setForm({...form,attending:true})}>Sim, estarei lá</Button><Button type="button" variant={form.attending===false?"default":"outline"} onClick={()=>setForm({...form,attending:false})}>Não poderei ir</Button></div>{form.attending&&<div className="mt-6 space-y-6"><Counter label="Acompanhantes adultos" value={form.guests} onChange={n=>setForm({...form,guests:n,guestNames:Array(n).fill("").map((_,i)=>form.guestNames[i]||"")})}/><Names count={form.guests} label="Nome do acompanhante" values={form.guestNames} onChange={v=>setForm({...form,guestNames:v})}/><Counter label="Crianças" value={form.children} onChange={n=>setForm({...form,children:n,childNames:Array(n).fill("").map((_,i)=>form.childNames[i]||"")})}/><Names count={form.children} label="Nome da criança" values={form.childNames} onChange={v=>setForm({...form,childNames:v})}/><Counter label="Ajuda (babá, motorista ou apoio)" value={form.helpers} onChange={n=>setForm({...form,helpers:n,helperNames:Array(n).fill("").map((_,i)=>form.helperNames[i]||"")})}/><Names count={form.helpers} label="Nome" values={form.helperNames} onChange={v=>setForm({...form,helperNames:v})}/></div>}<Label className="mt-6 block">Seu WhatsApp</Label><Input className="mt-2 h-12" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})} placeholder="(31) 99999-9999"/><Button type="submit" size="lg" className="mt-7 w-full"><Check/>Enviar confirmação</Button>{status&&<p className="mt-4 text-center text-sm">{status}</p>}</form></div></section>
<section id="presentes" className="bg-primary px-5 py-24 text-primary-foreground"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-xs font-semibold uppercase text-secondary">Com carinho</p><h2 className="mt-3 text-5xl">Lista de presentes</h2><p className="mt-4 text-primary-foreground/75">Se preferir nos presentear com um Pix, escolha um item.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{gifts.map(g=><article className="bg-background text-foreground" key={g.id}>{g.image_url?<img src={g.image_url} alt={g.name} className="aspect-[4/3] w-full object-cover" loading="lazy"/>:<div className="flex aspect-[4/3] items-center justify-center bg-secondary"><Gift className="size-14 text-accent"/></div>}<div className="p-5"><h3 className="text-2xl">{g.name}</h3><p className="mt-1 text-muted-foreground">R$ {Number(g.price).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p><Button className="mt-5 w-full" disabled={g.is_given} onClick={()=>setGift(g)}>{g.is_given?"Já presenteado":"Presentear via Pix"}</Button></div></article>)}</div></div></section>
<section className="px-5 py-20 text-center"><h2 className="text-4xl">Fale conosco</h2><p className="mt-3 text-muted-foreground">Qualquer dúvida, é só chamar no WhatsApp.</p>{wedding.whatsapp&&<Button asChild className="mt-6"><a target="_blank" rel="noreferrer" href={`https://wa.me/${wedding.whatsapp}?text=${encodeURIComponent(`Olá! Vi o site do casamento de ${wedding.couple_names}`)}`}><MessageCircle/>Chamar no WhatsApp</a></Button>}</section><footer className="border-t border-border px-5 py-8 text-center text-sm text-muted-foreground">Feito com carinho para {wedding.couple_names} · {wedding.date_text}</footer>
<Dialog open={Boolean(gift)} onOpenChange={o=>!o&&setGift(null)}><DialogContent><DialogHeader><DialogTitle>{gift?.name}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Copie o código Pix e cole no aplicativo do seu banco.</p>{pix?<><div className="max-h-36 overflow-auto break-all bg-muted p-4 font-mono text-xs">{pix}</div><Button onClick={()=>navigator.clipboard.writeText(pix)}><Copy/>Copiar código Pix</Button></>:<p>Os noivos ainda não configuraram a chave Pix.</p>}</DialogContent></Dialog></main>}
function VenueSection({id,eyebrow,title,value}:{id:string;eyebrow:string;title:string;value:Wedding["ceremony"]}){return <section id={id} className="px-5 py-20"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-2"><div className="bg-background p-8"><p className="text-xs font-semibold uppercase text-accent">{eyebrow}</p><h2 className="mt-3 text-5xl">{title}</h2><h3 className="mt-10 text-2xl">{value.local}</h3><div className="mt-5 space-y-2 text-muted-foreground"><p>{value.data} · {value.hora}</p><p className="flex gap-2"><MapPin className="mt-1 size-4 shrink-0"/>{value.endereco}</p></div></div><iframe title={`Mapa de ${value.local}`} className="min-h-80 w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={`https://www.google.com/maps?q=${encodeURIComponent(value.endereco)}&output=embed`}/></div>{value.fotos.length>0&&<div className="mx-auto mt-6 grid max-w-6xl gap-3 sm:grid-cols-2">{value.fotos.map((url,i)=><img key={url} src={url} alt={`${value.local} ${i+1}`} loading="lazy" className="aspect-video w-full object-cover"/>)}</div>}</section>}
function Counter({label,value,onChange}:{label:string;value:number;onChange:(n:number)=>void}){return <div className="flex items-center justify-between"><Label>{label}</Label><div className="flex items-center gap-3"><Button type="button" size="icon" variant="outline" onClick={()=>onChange(Math.max(0,value-1))}><Minus/></Button><span className="w-5 text-center">{value}</span><Button type="button" size="icon" variant="outline" onClick={()=>onChange(Math.min(20,value+1))}><Plus/></Button></div></div>}
function Names({count,label,values,onChange}:{count:number;label:string;values:string[];onChange:(v:string[])=>void}){return <div className="space-y-2">{Array.from({length:count},(_,i)=><Input key={i} placeholder={`${label} ${i+1}`} value={values[i]||""} onChange={e=>{const copy=[...values];copy[i]=e.target.value;onChange(copy)}}/>)}</div>}
