import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Check, Download, Heart, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { lovable } from "@/integrations/lovable";
import { supabase } from "@/integrations/supabase/client";
import hero from "@/assets/wedding-hero.jpg";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "Laço — Site de casamento personalizado" }, { name: "description", content: "Crie seu site, envie fotos e acompanhe confirmações." }, { property: "og:title", content: "Laço — Site de casamento personalizado" }, { property: "og:description", content: "Tudo do seu casamento em um lugar bonito e simples." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Home });
function Home() { const navigate = useNavigate(); async function start() { const { data } = await supabase.auth.getUser(); if (data.user) { navigate({ to: "/painel" }); return; } const result = await lovable.auth.signInWithOAuth("google", { redirect_uri: window.location.origin }); if (!result.error && !result.redirected) navigate({ to: "/painel" }); }
return <main><section className="relative flex min-h-[92vh] items-end overflow-hidden px-5 pb-16 pt-28 md:px-12 md:pb-20"><img src={hero} alt="Casamento ao ar livre" className="absolute inset-0 h-full w-full object-cover" width={1920} height={1080}/><div className="absolute inset-0 bg-gradient-to-t from-foreground/80 via-foreground/20 to-transparent"/><nav className="absolute left-0 right-0 top-0 z-10 flex items-center justify-between px-5 py-6 text-primary-foreground md:px-12"><span className="font-serif text-3xl">Laço</span><Button variant="hero" onClick={start}>Entrar</Button></nav><div className="relative z-10 max-w-4xl animate-rise text-primary-foreground"><p className="mb-4 text-xs font-semibold uppercase">Seu casamento começa aqui</p><h1 className="max-w-3xl text-6xl leading-[.9] md:text-8xl">Memórias lindas.<br/>Organização leve.</h1><p className="mt-6 max-w-xl text-base text-primary-foreground/85 md:text-lg">Um site elegante para os convidados e uma área completa para vocês cuidarem de cada detalhe.</p><Button variant="hero" size="lg" onClick={start} className="mt-8">Criar meu site <ArrowRight/></Button></div></section><section className="bg-background px-5 py-24 md:px-12"><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase text-accent">Tudo em um lugar</p><div className="mt-4 grid gap-10 md:grid-cols-[1fr_1.2fr]"><h2 className="text-5xl leading-none md:text-6xl">Menos planilhas.<br/>Mais celebração.</h2><div className="grid gap-4 sm:grid-cols-2">{[[Heart,"Site com a história de vocês"],[Users,"Convidados e acompanhantes"],[Check,"Confirmações em tempo real"],[Download,"Relatório pronto para baixar"]].map(([Icon,label]) => { const C=Icon as typeof Heart; return <div className="border-t border-border py-5" key={label as string}><C className="mb-5 text-accent"/><p className="font-medium">{label as string}</p></div>;})}</div></div></div></section><footer className="flex flex-col justify-between gap-3 border-t border-border px-5 py-8 text-sm text-muted-foreground md:flex-row md:px-12"><span className="font-serif text-xl text-primary">Laço</span><span>Feito para celebrar histórias de amor.</span><Link to="/auth">Área do casal</Link></footer></main>; }
