import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, BarChart3, Check, Download, ExternalLink, Gift, Heart, LayoutTemplate, LogOut, Palette, Save, Search, Sparkles, Trash2, Type, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { PhotoUpload } from "@/components/wedding/photo-upload";
import { asPix, asTheme, asVenue, defaultTheme, formatWeddingDate, slugify, weddingSections, type Venue, type Wedding, type WeddingSection, type WeddingTheme } from "@/lib/wedding";
import type { Json, Tables } from "@/integrations/supabase/types";

type RSVP = Tables<"rsvps">; type GiftRow = Tables<"gifts">;
const tabs = [["resumo","Resumo"],["site","Conteúdo"],["aparencia","Aparência e layout"],["presentes","Presentes"],["confirmacoes","Confirmações"]] as const;
const sectionLabels: Record<WeddingSection,string> = { story:"Nossa história", ceremony:"Cerimônia", reception:"Recepção", rsvp:"Confirmar presença", gifts:"Presentes", contact:"Contato" };
const templateOptions: {id:WeddingTheme["template"];name:string;description:string;theme:WeddingTheme}[] = [
  {id:"garden",name:"Jardim romântico",description:"Delicado, orgânico e acolhedor.",theme:{...defaultTheme}},
  {id:"editorial",name:"Editorial contemporâneo",description:"Tipografia marcante e composição limpa.",theme:{...defaultTheme,template:"editorial",palette:"terracotta",font:"modern",heroAlign:"left"}},
  {id:"classic",name:"Clássico atemporal",description:"Elegante, simétrico e tradicional.",theme:{...defaultTheme,template:"classic",palette:"ocean",font:"classic"}},
];

export const Route = createFileRoute("/_authenticated/painel")({ head: () => ({ meta: [{ title: "Painel do casal — Laço" }, { name: "description", content: "Edite o site, as fotos e acompanhe confirmações." }, { property: "og:title", content: "Painel do casal — Laço" }, { property: "og:description", content: "Área privada de organização do casamento." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Dashboard });

function Dashboard() {
  const { user } = Route.useRouteContext(); const navigate = useNavigate();
  const [wedding,setWedding]=useState<Wedding|null>(null); const [rsvps,setRsvps]=useState<RSVP[]>([]); const [gifts,setGifts]=useState<GiftRow[]>([]);
  const [search,setSearch]=useState(""); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(""); const [setupStep,setSetupStep]=useState(1);
  const [newGift,setNewGift]=useState({name:"",price:"",image_url:""});
  useEffect(()=>{ void load(); },[]);
  async function load(){
    let {data:w}=await supabase.from("weddings").select("*").eq("owner_id",user.id).maybeSingle();
    if(!w){
      const display=String(user.user_metadata?.["full_name"]||user.email?.split("@")[0]||"");
      await supabase.from("profiles").upsert({id:user.id,display_name:display,avatar_url:String(user.user_metadata?.["avatar_url"]||"")||null});
      const created=await supabase.from("weddings").insert({owner_id:user.id,slug:`casamento-${user.id.slice(0,8)}`,couple_names:"Nosso casamento",partner_one_name:"",partner_two_name:"",setup_completed:false}).select().single(); w=created.data;
      if(w) await supabase.from("gifts").insert([{wedding_id:w.id,owner_id:user.id,name:"Lua de mel",price:200},{wedding_id:w.id,owner_id:user.id,name:"Jantar romântico",price:100},{wedding_id:w.id,owner_id:user.id,name:"Jogo de panelas",price:150}]);
    }
    if(!w)return;
    setWedding({...w,ceremony:asVenue(w.ceremony),reception:asVenue(w.reception),pix:asPix(w.pix),theme:asTheme(w.theme)} as Wedding);
    const [rr,gg]=await Promise.all([supabase.from("rsvps").select("*").eq("wedding_id",w.id).order("created_at",{ascending:false}),supabase.from("gifts").select("*").eq("wedding_id",w.id).order("created_at")]);
    setRsvps(rr.data||[]); setGifts(gg.data||[]);
  }
  const set=<K extends keyof Wedding>(key:K,value:Wedding[K])=>wedding&&setWedding({...wedding,[key]:value});
  const setTheme=<K extends keyof WeddingTheme>(key:K,value:WeddingTheme[K])=>wedding&&setWedding({...wedding,theme:{...wedding.theme,[key]:value}});
  async function persist(done=false){ if(!wedding)return false; setSaving(true); setNotice(""); const names=`${wedding.partner_one_name.trim()} & ${wedding.partner_two_name.trim()}`; const payload={couple_names:names,partner_one_name:wedding.partner_one_name.trim(),partner_one_role:wedding.partner_one_role,partner_two_name:wedding.partner_two_name.trim(),partner_two_role:wedding.partner_two_role,wedding_at:wedding.wedding_at,date_text:formatWeddingDate(wedding.wedding_at),cover_photo:wedding.cover_photo,story:wedding.story,whatsapp:wedding.whatsapp,slug:wedding.slug,ceremony:wedding.ceremony as unknown as Json,reception:wedding.reception as unknown as Json,pix:wedding.pix as unknown as Json,theme:wedding.theme as unknown as Json,is_published:wedding.is_published,setup_completed:done||wedding.setup_completed}; const {error}=await supabase.from("weddings").update(payload).eq("id",wedding.id); setSaving(false); if(error){setNotice("Não foi possível salvar. Tente novamente.");return false;} setWedding({...wedding,...payload,ceremony:wedding.ceremony,reception:wedding.reception,pix:wedding.pix,theme:wedding.theme} as Wedding);setNotice("Alterações salvas.");return true; }
  async function finishSetup(){ if(!wedding?.partner_one_name.trim()||!wedding.partner_two_name.trim()||!wedding.wedding_at){setNotice("Preencha os dois nomes, os papéis, a data e a hora.");return;} await persist(true); }
  async function addGift(){if(!wedding||!newGift.name||!Number(newGift.price))return;await supabase.from("gifts").insert({wedding_id:wedding.id,owner_id:user.id,name:newGift.name,price:Number(newGift.price),image_url:newGift.image_url||null});setNewGift({name:"",price:"",image_url:""});await load();}
  async function updateGift(g:GiftRow,changes:Partial<GiftRow>){await supabase.from("gifts").update(changes).eq("id",g.id);await load();}
  async function deleteGift(g:GiftRow){if(g.image_url&&!/^https?:\/\//.test(g.image_url))await supabase.storage.from("wedding-photos").remove([g.image_url]);await supabase.from("gifts").delete().eq("id",g.id);await load();}
  async function signOut(){await supabase.auth.signOut();navigate({to:"/auth",replace:true});}
  const stats=useMemo(()=>({yes:rsvps.filter(r=>r.attending).length,no:rsvps.filter(r=>!r.attending).length,people:rsvps.filter(r=>r.attending).reduce((n,r)=>n+1+r.guest_count+r.children_count+r.helpers_count,0)}),[rsvps]);
  const filtered=rsvps.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));
  function exportCsv(){const q=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const rows=[["Nome","Vai?","Adultos","Crianças","Ajuda","WhatsApp","Data"],...rsvps.map(r=>[r.name,r.attending?"Sim":"Não",r.guest_count,r.children_count,r.helpers_count,r.whatsapp,new Date(r.created_at).toLocaleString("pt-BR")])];const blob=new Blob(["\ufeff"+rows.map(x=>x.map(q).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="confirmacoes.csv";a.click();URL.revokeObjectURL(a.href);}
  if(!wedding)return <main className="flex min-h-screen items-center justify-center"><p className="text-muted-foreground">Preparando seu casamento…</p></main>;
  if(!wedding.setup_completed)return <Onboarding wedding={wedding} step={setupStep} setStep={setSetupStep} set={set} finish={finishSetup} saving={saving} notice={notice}/>;
  return <main className="min-h-screen bg-muted/40"><header className="border-b border-border bg-background"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link to="/" className="font-serif text-3xl text-primary">Laço</Link><div className="flex items-center gap-2"><Button variant="outline" asChild><Link to="/casamento/$slug" params={{slug:wedding.slug}} target="_blank"><ExternalLink/> Ver site</Link></Button><Button variant="ghost" size="icon" onClick={signOut} title="Sair"><LogOut/></Button></div></div></header><div className="mx-auto max-w-7xl px-5 py-10"><p className="text-xs font-semibold uppercase text-accent">Painel do casal</p><h1 className="mt-2 text-4xl md:text-5xl">Olá, {wedding.couple_names}</h1><Tabs defaultValue="resumo" className="mt-8"><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-none border-b border-border bg-transparent p-0">{tabs.map(([v,l])=><TabsTrigger key={v} value={v} className="rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-primary data-[state=active]:shadow-none">{l}</TabsTrigger>)}</TabsList>
  <TabsContent value="resumo" className="mt-8"><div className="grid gap-4 md:grid-cols-3">{[[Heart,"Confirmaram",stats.yes],[Users,"Total de pessoas",stats.people],[BarChart3,"Não poderão ir",stats.no]].map(([Icon,label,n])=>{const C=Icon as typeof Heart;return <div className="border border-border bg-background p-6" key={label as string}><C className="text-accent"/><p className="mt-8 text-sm text-muted-foreground">{label as string}</p><strong className="font-serif text-5xl font-normal">{n as number}</strong></div>})}</div><Editor title="Seu endereço"><p className="text-sm text-muted-foreground">Compartilhe este endereço com os convidados.</p><div className="mt-4 flex flex-wrap items-center gap-3"><code className="max-w-full overflow-hidden bg-muted px-3 py-2 text-sm">/casamento/{wedding.slug}</code><Button variant="outline" onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/casamento/${wedding.slug}`)}>Copiar</Button></div></Editor></TabsContent>
  <TabsContent value="site" className="mt-8"><div className="grid gap-8 lg:grid-cols-2"><Editor title="Informações principais"><div className="grid gap-4 sm:grid-cols-2"><PersonField label="Primeira pessoa" wedding={wedding} nameKey="partner_one_name" roleKey="partner_one_role" set={set}/><PersonField label="Segunda pessoa" wedding={wedding} nameKey="partner_two_name" roleKey="partner_two_role" set={set}/></div><Label>Endereço público</Label><Input value={wedding.slug} onChange={e=>set("slug",slugify(e.target.value))}/><Label>Data e hora</Label><Input type="datetime-local" value={wedding.wedding_at.slice(0,16)} onChange={e=>set("wedding_at",new Date(e.target.value).toISOString())}/><PhotoUpload ownerId={user.id} folder="cover" label="Foto principal" value={wedding.cover_photo} onChange={v=>set("cover_photo",v)}/><Label>Nossa história</Label><Textarea className="min-h-32" value={wedding.story} onChange={e=>set("story",e.target.value)}/><Label>WhatsApp</Label><Input value={wedding.whatsapp} onChange={e=>set("whatsapp",e.target.value.replace(/\D/g,""))}/></Editor><div className="space-y-8"><VenueEditor ownerId={user.id} title="Cerimônia" folder="ceremony" value={wedding.ceremony} onChange={v=>set("ceremony",v)}/><VenueEditor ownerId={user.id} title="Recepção" folder="reception" value={wedding.reception} onChange={v=>set("reception",v)}/><Editor title="Pix"><Label>Chave Pix</Label><Input value={wedding.pix.key} onChange={e=>set("pix",{...wedding.pix,key:e.target.value})}/><Label>Nome do recebedor</Label><Input value={wedding.pix.name} onChange={e=>set("pix",{...wedding.pix,name:e.target.value})}/><Label>Cidade</Label><Input value={wedding.pix.city} onChange={e=>set("pix",{...wedding.pix,city:e.target.value})}/></Editor></div></div><SaveBar saving={saving} notice={notice} onSave={()=>void persist()}/></TabsContent>
  <TabsContent value="aparencia" className="mt-8"><div className="grid gap-8 xl:grid-cols-[1fr_.85fr]"><div className="space-y-8"><Editor title="Modelos prontos"><div className="grid gap-3 md:grid-cols-3">{templateOptions.map(option=><button key={option.id} type="button" onClick={()=>set("theme",{...option.theme,sections:[...wedding.theme.sections],hidden:[...wedding.theme.hidden]})} className={`border p-4 text-left transition ${wedding.theme.template===option.id?"border-primary bg-secondary":"border-border bg-background hover:border-primary"}`}><LayoutTemplate className="mb-6 text-accent"/><strong>{option.name}</strong><p className="mt-1 text-xs text-muted-foreground">{option.description}</p></button>)}</div></Editor><Editor title="Personalização"><ChoiceGrid icon={Palette} label="Cores" value={wedding.theme.palette} options={[["olive","Verde oliva"],["rose","Rosa antigo"],["ocean","Azul sereno"],["terracotta","Terracota"]]} onChange={v=>setTheme("palette",v as WeddingTheme["palette"])}/><ChoiceGrid icon={Type} label="Tipografia" value={wedding.theme.font} options={[["romantic","Romântica"],["modern","Moderna"],["classic","Clássica"]]} onChange={v=>setTheme("font",v as WeddingTheme["font"])}/><ChoiceGrid icon={Sparkles} label="Ícones" value={wedding.theme.icons} options={[["minimal","Minimalistas"],["floral","Florais"],["classic","Clássicos"]]} onChange={v=>setTheme("icons",v as WeddingTheme["icons"])}/><ChoiceGrid icon={LayoutTemplate} label="Alinhamento da abertura" value={wedding.theme.heroAlign} options={[["center","Centralizado"],["left","À esquerda"]]} onChange={v=>setTheme("heroAlign",v as WeddingTheme["heroAlign"])}/></Editor><Editor title="Ordem das seções"><div className="divide-y divide-border">{wedding.theme.sections.map((section,index)=><div key={section} className="flex items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="font-medium">{sectionLabels[section]}</p></div><Switch aria-label={`Exibir ${sectionLabels[section]}`} checked={!wedding.theme.hidden.includes(section)} onCheckedChange={checked=>setTheme("hidden",checked?wedding.theme.hidden.filter(x=>x!==section):[...wedding.theme.hidden,section])}/><Button size="icon" variant="ghost" title="Mover para cima" disabled={index===0} onClick={()=>setTheme("sections",move(wedding.theme.sections,index,-1))}><ArrowUp/></Button><Button size="icon" variant="ghost" title="Mover para baixo" disabled={index===wedding.theme.sections.length-1} onClick={()=>setTheme("sections",move(wedding.theme.sections,index,1))}><ArrowDown/></Button></div>)}</div></Editor></div><div className="xl:sticky xl:top-6 xl:self-start"><p className="mb-3 text-sm font-medium">Prévia ao vivo</p><ThemePreview wedding={wedding}/></div></div><SaveBar saving={saving} notice={notice} onSave={()=>void persist()}/></TabsContent>
  <TabsContent value="presentes" className="mt-8"><Editor title="Lista de presentes"><div className="grid gap-4 lg:grid-cols-3"><div className="space-y-3"><Input placeholder="Nome do presente" value={newGift.name} onChange={e=>setNewGift({...newGift,name:e.target.value})}/><Input placeholder="Valor" type="number" value={newGift.price} onChange={e=>setNewGift({...newGift,price:e.target.value})}/><PhotoUpload ownerId={user.id} folder="gifts" label="Foto do presente" value={newGift.image_url} onChange={image_url=>setNewGift({...newGift,image_url})}/><Button onClick={addGift} className="w-full"><Gift/>Adicionar presente</Button></div><div className="space-y-3 lg:col-span-2">{gifts.map(g=><div key={g.id} className="grid gap-4 border border-border p-4 sm:grid-cols-[1fr_220px_auto] sm:items-center"><div><strong>{g.name}</strong><p className="text-sm text-muted-foreground">R$ {Number(g.price).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div><PhotoUpload ownerId={user.id} folder="gifts" label="Imagem" value={g.image_url||""} onChange={image_url=>void updateGift(g,{image_url:image_url||null})}/><Button size="icon" variant="ghost" title="Excluir presente" onClick={()=>void deleteGift(g)}><Trash2/></Button></div>)}</div></div></Editor></TabsContent>
  <TabsContent value="confirmacoes" className="mt-8"><div className="border border-border bg-background p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-3xl">Confirmações</h2><p className="text-sm text-muted-foreground">{rsvps.length} respostas recebidas</p></div><Button onClick={exportCsv}><Download/>Baixar CSV</Button></div><div className="relative mt-6 max-w-sm"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar por nome" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="overflow-x-auto"><Table className="mt-5"><TableHeader><TableRow><TableHead>Nome</TableHead><TableHead>Presença</TableHead><TableHead>Pessoas</TableHead><TableHead>WhatsApp</TableHead></TableRow></TableHeader><TableBody>{filtered.map(r=><TableRow key={r.id}><TableCell className="font-medium">{r.name}</TableCell><TableCell>{r.attending?"Sim":"Não"}</TableCell><TableCell>{r.attending?1+r.guest_count+r.children_count+r.helpers_count:0}</TableCell><TableCell>{r.whatsapp||"—"}</TableCell></TableRow>)}</TableBody></Table></div></div></TabsContent>
  </Tabs></div></main>;
}

function Onboarding({wedding,step,setStep,set,finish,saving,notice}:{wedding:Wedding;step:number;setStep:(n:number)=>void;set:<K extends keyof Wedding>(key:K,value:Wedding[K])=>void;finish:()=>void;saving:boolean;notice:string}){return <main className="min-h-screen bg-secondary/40 px-5 py-10"><div className="mx-auto max-w-2xl"><p className="font-serif text-3xl text-primary">Laço</p><div className="mt-10 flex gap-2">{[1,2].map(n=><div key={n} className={`h-1 flex-1 ${n<=step?"bg-primary":"bg-border"}`}/>)}</div><div className="mt-8 bg-background p-6 shadow-xl md:p-10">{step===1?<><p className="text-xs font-semibold uppercase text-accent">Primeiro passo</p><h1 className="mt-2 text-4xl">Quem vai se casar?</h1><p className="mt-3 text-muted-foreground">Essas informações já deixam o site pronto para vocês.</p><div className="mt-8 grid gap-6 sm:grid-cols-2"><PersonField label="Primeira pessoa" wedding={wedding} nameKey="partner_one_name" roleKey="partner_one_role" set={set}/><PersonField label="Segunda pessoa" wedding={wedding} nameKey="partner_two_name" roleKey="partner_two_role" set={set}/></div><div className="mt-6"><Label>Data e hora do casamento</Label><Input className="mt-2 h-11" type="datetime-local" value={wedding.wedding_at.slice(0,16)} onChange={e=>set("wedding_at",new Date(e.target.value).toISOString())}/></div><Button className="mt-8 w-full" size="lg" onClick={()=>setStep(2)}>Continuar</Button></>:<><p className="text-xs font-semibold uppercase text-accent">Último passo</p><h1 className="mt-2 text-4xl">Onde será?</h1><p className="mt-3 text-muted-foreground">Preencha o que já souber. Os locais podem ficar para depois.</p><div className="mt-8 grid gap-6 sm:grid-cols-2"><SimpleVenue title="Cerimônia" value={wedding.ceremony} onChange={v=>set("ceremony",v)}/><SimpleVenue title="Recepção" value={wedding.reception} onChange={v=>set("reception",v)}/></div>{notice&&<p className="mt-5 text-sm text-destructive">{notice}</p>}<div className="mt-8 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><Button variant="ghost" onClick={()=>setStep(1)}>Voltar</Button><div className="flex flex-col gap-3 sm:flex-row"><Button variant="outline" onClick={finish} disabled={saving}>Responder locais depois</Button><Button onClick={finish} disabled={saving}>{saving?"Criando…":"Criar meu site"}<Check/></Button></div></div></>}</div></div></main>}
function PersonField({label,wedding,nameKey,roleKey,set}:{label:string;wedding:Wedding;nameKey:"partner_one_name"|"partner_two_name";roleKey:"partner_one_role"|"partner_two_role";set:<K extends keyof Wedding>(key:K,value:Wedding[K])=>void}){return <div className="space-y-2"><Label>{label}</Label><Input placeholder="Nome" value={wedding[nameKey]} onChange={e=>set(nameKey,e.target.value)}/><Select value={wedding[roleKey]} onValueChange={v=>set(roleKey,v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="noiva">Noiva</SelectItem><SelectItem value="noivo">Noivo</SelectItem></SelectContent></Select></div>}
function SimpleVenue({title,value,onChange}:{title:string;value:Venue;onChange:(v:Venue)=>void}){return <div className="space-y-3"><h2 className="text-2xl">{title}</h2><Input placeholder="Nome do local" value={value.local} onChange={e=>onChange({...value,local:e.target.value})}/><Input placeholder="Endereço" value={value.endereco} onChange={e=>onChange({...value,endereco:e.target.value})}/></div>}
function Editor({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-8 border border-border bg-background p-6 first:mt-0"><h2 className="mb-6 text-3xl">{title}</h2><div className="space-y-4">{children}</div></section>}
function VenueEditor({ownerId,title,folder,value,onChange}:{ownerId:string;title:string;folder:string;value:Venue;onChange:(v:Venue)=>void}){return <Editor title={title}><Label>Nome do local</Label><Input value={value.local} onChange={e=>onChange({...value,local:e.target.value})}/><div className="grid gap-4 sm:grid-cols-2"><div><Label>Data</Label><Input className="mt-2" value={value.data} onChange={e=>onChange({...value,data:e.target.value})}/></div><div><Label>Horário</Label><Input className="mt-2" value={value.hora} onChange={e=>onChange({...value,hora:e.target.value})}/></div></div><Label>Endereço</Label><Input value={value.endereco} onChange={e=>onChange({...value,endereco:e.target.value})}/><div className="grid gap-4 sm:grid-cols-2">{value.fotos.map((photo,index)=><PhotoUpload key={`${photo}-${index}`} ownerId={ownerId} folder={folder} label={`Foto ${index+1}`} value={photo} onChange={next=>onChange({...value,fotos:value.fotos.map((item,i)=>i===index?next:item).filter(Boolean)})}/>)}</div><PhotoUpload ownerId={ownerId} folder={folder} label="Adicionar foto" value="" onChange={photo=>onChange({...value,fotos:[...value.fotos,photo]})}/></Editor>}
function ChoiceGrid({icon:Icon,label,value,options,onChange}:{icon:typeof Palette;label:string;value:string;options:string[][];onChange:(v:string)=>void}){return <div><p className="mb-3 flex items-center gap-2 text-sm font-medium"><Icon className="size-4"/>{label}</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{options.map(([id,name])=><Button type="button" key={id} variant={value===id?"default":"outline"} onClick={()=>onChange(id)}>{name}</Button>)}</div></div>}
function move(items:WeddingSection[],index:number,offset:number){const copy=[...items];const target=index+offset;[copy[index],copy[target]]=[copy[target],copy[index]];return copy}
function ThemePreview({wedding}:{wedding:Wedding}){return <div className={`wedding-theme wedding-palette-${wedding.theme.palette} wedding-font-${wedding.theme.font} overflow-hidden border border-border bg-background shadow-xl`}><div className={`flex aspect-[4/3] flex-col justify-end bg-primary p-8 text-primary-foreground ${wedding.theme.heroAlign==="center"?"items-center text-center":"items-start text-left"}`}><span className="text-xs uppercase">Nós vamos nos casar</span><h2 className="mt-3 text-5xl leading-none">{wedding.partner_one_name||"Nome"} & {wedding.partner_two_name||"Nome"}</h2><p className="mt-4 text-sm">{formatWeddingDate(wedding.wedding_at)}</p></div><div className="space-y-3 p-5">{wedding.theme.sections.filter(x=>!wedding.theme.hidden.includes(x)).map(section=><div key={section} className="border-b border-border pb-3 text-sm">{sectionLabels[section]}</div>)}</div></div>}
function SaveBar({saving,notice,onSave}:{saving:boolean;notice:string;onSave:()=>void}){return <div className="mt-6 flex flex-wrap items-center gap-4"><Button size="lg" onClick={onSave} disabled={saving}><Save/>{saving?"Salvando…":"Salvar alterações"}</Button>{notice&&<p className="text-sm text-muted-foreground">{notice}</p>}</div>}