import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Download, ExternalLink, Gift, Heart, LogOut, Save, Search, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { asPix, asVenue, slugify, type Wedding } from "@/lib/wedding";
import type { Tables } from "@/integrations/supabase/types";

type RSVP = Tables<"rsvps">; type GiftRow = Tables<"gifts">;
export const Route = createFileRoute("/_authenticated/painel")({ head: () => ({ meta: [{ title: "Painel do casal — Laço" }, { name: "description", content: "Gerencie seu site e suas confirmações." }, { property: "og:title", content: "Painel do casal — Laço" }, { property: "og:description", content: "Área privada de organização do casamento." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Dashboard });
const tabs = [["resumo","Resumo"],["site","Site"],["convidados","Convidados"],["presentes","Presentes"],["confirmacoes","Confirmações"]] as const;
function Dashboard() {
 const { user } = Route.useRouteContext(); const navigate = useNavigate(); const [wedding,setWedding]=useState<Wedding|null>(null); const [rsvps,setRsvps]=useState<RSVP[]>([]); const [gifts,setGifts]=useState<GiftRow[]>([]); const [guestText,setGuestText]=useState(""); const [search,setSearch]=useState(""); const [saving,setSaving]=useState(false); const [newGift,setNewGift]=useState({name:"",price:"",image_url:""});
 useEffect(()=>{ void load(); },[]);
 async function load(){ let {data:w}=await supabase.from("weddings").select("*").eq("owner_id",user.id).maybeSingle(); if(!w){ const name=String(user.user_metadata?.["full_name"]||user.email?.split("@")[0]||"Nosso casamento"); const base=slugify(name)+"-"+user.id.slice(0,6); await supabase.from("profiles").upsert({id:user.id,display_name:name,avatar_url:String(user.user_metadata?.["avatar_url"]||"")||null}); const created=await supabase.from("weddings").insert({owner_id:user.id,slug:base}).select().single(); w=created.data; if(w) await supabase.from("gifts").insert([{wedding_id:w.id,owner_id:user.id,name:"Lua de mel",price:200},{wedding_id:w.id,owner_id:user.id,name:"Jantar romântico",price:100},{wedding_id:w.id,owner_id:user.id,name:"Jogo de panelas",price:150}]); } if(!w)return; setWedding({...w,ceremony:asVenue(w.ceremony),reception:asVenue(w.reception),pix:asPix(w.pix)} as Wedding); const [rr,gg,gl]=await Promise.all([supabase.from("rsvps").select("*").eq("wedding_id",w.id).order("created_at",{ascending:false}),supabase.from("gifts").select("*").eq("wedding_id",w.id),supabase.from("guests").select("name").eq("wedding_id",w.id).order("name")]); setRsvps(rr.data||[]);setGifts(gg.data||[]);setGuestText((gl.data||[]).map(x=>x.name).join("\n")); }
 async function saveWedding(){if(!wedding)return;setSaving(true);await supabase.from("weddings").update({couple_names:wedding.couple_names,wedding_at:wedding.wedding_at,date_text:wedding.date_text,cover_photo:wedding.cover_photo,story:wedding.story,whatsapp:wedding.whatsapp,slug:wedding.slug,ceremony:wedding.ceremony,reception:wedding.reception,pix:wedding.pix,is_published:wedding.is_published}).eq("id",wedding.id);setSaving(false);}
 async function saveGuests(){if(!wedding)return;setSaving(true);await supabase.from("guests").delete().eq("wedding_id",wedding.id);const names=[...new Set(guestText.split("\n").map(x=>x.trim()).filter(Boolean))];if(names.length)await supabase.from("guests").insert(names.map(name=>({wedding_id:wedding.id,owner_id:user.id,name,normalized_name:name.toLocaleLowerCase("pt-BR")})));setSaving(false);}
 async function addGift(){if(!wedding||!newGift.name||!Number(newGift.price))return;await supabase.from("gifts").insert({wedding_id:wedding.id,owner_id:user.id,name:newGift.name,price:Number(newGift.price),image_url:newGift.image_url||null});setNewGift({name:"",price:"",image_url:""});await load();}
 async function toggleGift(g:GiftRow){await supabase.from("gifts").update({is_given:!g.is_given}).eq("id",g.id);await load();}
 async function signOut(){await supabase.auth.signOut();navigate({to:"/auth",replace:true});}
 const stats=useMemo(()=>({yes:rsvps.filter(r=>r.attending).length,no:rsvps.filter(r=>!r.attending).length,people:rsvps.filter(r=>r.attending).reduce((n,r)=>n+1+r.guest_count+r.children_count+r.helpers_count,0)}),[rsvps]); const filtered=rsvps.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));
 function exportCsv(){const q=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const rows=[["Nome","Vai?","Adultos","Crianças","Ajuda","WhatsApp","Na lista","Data"],...rsvps.map(r=>[r.name,r.attending?"Sim":"Não",r.guest_count,r.children_count,r.helpers_count,r.whatsapp,r.on_list?"Sim":"Não",new Date(r.created_at).toLocaleString("pt-BR")])];const blob=new Blob(["\ufeff"+rows.map(x=>x.map(q).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="confirmacoes.csv";a.click();URL.revokeObjectURL(a.href);}
 if(!wedding)return <main className="flex min-h-screen items-center justify-center"><p className="text-muted-foreground">Preparando seu casamento…</p></main>;
 const set=(key:keyof Wedding,value:unknown)=>setWedding({...wedding,[key]:value}); const field="mt-2 h-11";
 return <main className="min-h-screen bg-muted/40"><header className="border-b border-border bg-background"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link to="/" className="font-serif text-3xl text-primary">Laço</Link><div className="flex items-center gap-2"><Button variant="outline" asChild><a href={`/casamento/${wedding.slug}`} target="_blank" rel="noreferrer"><ExternalLink/> Ver site</a></Button><Button variant="ghost" size="icon" onClick={signOut} title="Sair"><LogOut/></Button></div></div></header><div className="mx-auto max-w-7xl px-5 py-10"><p className="text-xs font-semibold uppercase text-accent">Painel do casal</p><h1 className="mt-2 text-5xl">Olá, {wedding.couple_names}</h1><Tabs defaultValue="resumo" className="mt-8"><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-none border-b border-border bg-transparent p-0">{tabs.map(([v,l])=><TabsTrigger key={v} value={v} className="rounded-none border-b-2 border-transparent px-5 py-3 data-[state=active]:border-primary data-[state=active]:shadow-none">{l}</TabsTrigger>)}</TabsList>
 <TabsContent value="resumo" className="mt-8"><div className="grid gap-4 md:grid-cols-3">{[[Heart,"Confirmaram",stats.yes],[Users,"Total de pessoas",stats.people],[BarChart3,"Não poderão ir",stats.no]].map(([Icon,label,n])=>{const C=Icon as typeof Heart;return <div className="border border-border bg-background p-6" key={label as string}><C className="text-accent"/><p className="mt-8 text-sm text-muted-foreground">{label as string}</p><strong className="font-serif text-5xl font-normal">{n as number}</strong></div>})}</div><div className="mt-8 border border-border bg-background p-6"><h2 className="text-2xl">Seu endereço</h2><p className="mt-2 text-sm text-muted-foreground">Compartilhe este link com os convidados.</p><div className="mt-4 flex flex-wrap items-center gap-3"><code className="bg-muted px-3 py-2 text-sm">{window.location.origin}/casamento/{wedding.slug}</code><Button variant="outline" onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/casamento/${wedding.slug}`)}>Copiar</Button></div></div></TabsContent>
 <TabsContent value="site" className="mt-8"><div className="grid gap-8 lg:grid-cols-2"><Editor title="Informações principais"><Label>Nomes do casal</Label><Input className={field} value={wedding.couple_names} onChange={e=>set("couple_names",e.target.value)}/><Label>Endereço público</Label><Input className={field} value={wedding.slug} onChange={e=>set("slug",slugify(e.target.value))}/><Label>Data e hora</Label><Input type="datetime-local" className={field} value={wedding.wedding_at.slice(0,16)} onChange={e=>set("wedding_at",new Date(e.target.value).toISOString())}/><Label>Data exibida</Label><Input className={field} value={wedding.date_text} onChange={e=>set("date_text",e.target.value)}/><Label>URL da foto de capa</Label><Input className={field} value={wedding.cover_photo} onChange={e=>set("cover_photo",e.target.value)}/><Label>Nossa história</Label><Textarea className="mt-2 min-h-32" value={wedding.story} onChange={e=>set("story",e.target.value)}/><Label>WhatsApp</Label><Input className={field} value={wedding.whatsapp} onChange={e=>set("whatsapp",e.target.value.replace(/\D/g,""))}/></Editor><div className="space-y-8"><VenueEditor title="Cerimônia" value={wedding.ceremony} onChange={v=>set("ceremony",v)}/><VenueEditor title="Recepção" value={wedding.reception} onChange={v=>set("reception",v)}/><Editor title="Pix"><Label>Chave Pix</Label><Input className={field} value={wedding.pix.key} onChange={e=>set("pix",{...wedding.pix,key:e.target.value})}/><Label>Nome do recebedor</Label><Input className={field} value={wedding.pix.name} onChange={e=>set("pix",{...wedding.pix,name:e.target.value})}/><Label>Cidade</Label><Input className={field} value={wedding.pix.city} onChange={e=>set("pix",{...wedding.pix,city:e.target.value})}/></Editor></div></div><Button onClick={saveWedding} disabled={saving} className="mt-6"><Save/> {saving?"Salvando…":"Salvar alterações"}</Button></TabsContent>
 <TabsContent value="convidados" className="mt-8"><Editor title="Lista de convidados"><p className="mb-5 text-sm text-muted-foreground">Um nome por linha. A lista serve para conferir discretamente quem recebeu o convite.</p><Textarea className="min-h-96" value={guestText} onChange={e=>setGuestText(e.target.value)}/><Button onClick={saveGuests} disabled={saving} className="mt-5"><Save/>Salvar lista</Button></Editor></TabsContent>
 <TabsContent value="presentes" className="mt-8"><Editor title="Lista de presentes"><div className="grid gap-3 md:grid-cols-4"><Input placeholder="Nome" value={newGift.name} onChange={e=>setNewGift({...newGift,name:e.target.value})}/><Input placeholder="Valor" type="number" value={newGift.price} onChange={e=>setNewGift({...newGift,price:e.target.value})}/><Input placeholder="URL da imagem" value={newGift.image_url} onChange={e=>setNewGift({...newGift,image_url:e.target.value})}/><Button onClick={addGift}><Gift/>Adicionar</Button></div><div className="mt-6 divide-y divide-border">{gifts.map(g=><div key={g.id} className="flex items-center justify-between gap-4 py-4"><div><strong>{g.name}</strong><p className="text-sm text-muted-foreground">R$ {Number(g.price).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div><Button variant="outline" onClick={()=>toggleGift(g)}>{g.is_given?"Tornar disponível":"Marcar presenteado"}</Button></div>)}</div></Editor></TabsContent>
 <TabsContent value="confirmacoes" className="mt-8"><div className="border border-border bg-background p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-3xl">Confirmações</h2><p className="text-sm text-muted-foreground">{rsvps.length} respostas recebidas</p></div><Button onClick={exportCsv}><Download/>Baixar CSV</Button></div><div className="relative mt-6 max-w-sm"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar por nome" value={search} onChange={e=>setSearch(e.target.value)}/></div><Table className="mt-5"><TableHeader><TableRow><TableHead>Nome</TableHead><TableHead>Presença</TableHead><TableHead>Pessoas</TableHead><TableHead>WhatsApp</TableHead><TableHead>Na lista</TableHead></TableRow></TableHeader><TableBody>{filtered.map(r=><TableRow key={r.id}><TableCell className="font-medium">{r.name}</TableCell><TableCell>{r.attending?"Sim":"Não"}</TableCell><TableCell>{r.attending?1+r.guest_count+r.children_count+r.helpers_count:0}</TableCell><TableCell>{r.whatsapp||"—"}</TableCell><TableCell>{r.on_list?"Sim":"Não"}</TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
 </Tabs></div></main>;
}
function Editor({title,children}:{title:string;children:React.ReactNode}){return <section className="border border-border bg-background p-6"><h2 className="mb-6 text-3xl">{title}</h2><div className="space-y-3">{children}</div></section>}
function VenueEditor({title,value,onChange}:{title:string;value:Wedding["ceremony"];onChange:(v:Wedding["ceremony"])=>void}){return <Editor title={title}><Label>Nome do local</Label><Input value={value.local} onChange={e=>onChange({...value,local:e.target.value})}/><Label>Data</Label><Input value={value.data} onChange={e=>onChange({...value,data:e.target.value})}/><Label>Horário</Label><Input value={value.hora} onChange={e=>onChange({...value,hora:e.target.value})}/><Label>Endereço</Label><Input value={value.endereco} onChange={e=>onChange({...value,endereco:e.target.value})}/><Label>Fotos (uma URL por linha)</Label><Textarea value={value.fotos.join("\n")} onChange={e=>onChange({...value,fotos:e.target.value.split("\n").map(x=>x.trim()).filter(Boolean)})}/></Editor>}
