import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, BarChart3, Check, Download, ExternalLink, Gift, Heart, LayoutTemplate, LogOut, MessageSquare, Palette, Save, Search, ShieldCheck, Sparkles, Trash2, Type, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { PhotoUpload } from "@/components/wedding/photo-upload";
import { asPix, asTheme, asVenue, combineWeddingDateTime, defaultTheme, formatWeddingDate, slugify, weddingDatePart, weddingThemeStyle, weddingTimePart, type Venue, type Wedding, type WeddingSection, type WeddingTheme } from "@/lib/wedding";
import type { Json, Tables } from "@/integrations/supabase/types";

import { Printer } from "lucide-react";

type RSVP = Tables<"rsvps">; type GiftRow = Tables<"gifts">; type GiftMessage = Tables<"gift_messages">;
const tabs = [["resumo","Resumo"],["site","Conteúdo"],["aparencia","Aparência e layout"],["presentes","Presentes"],["confirmacoes","Confirmações"],["mural","Mural"],["acompanhamento","Acompanhamento"]] as const;
const sectionLabels: Record<WeddingSection,string> = { story:"Nossa história", ceremony:"Cerimônia", reception:"Recepção", rsvp:"Confirmar presença", gifts:"Presentes", contact:"Contato" };
const templateOptions: {id:WeddingTheme["template"];name:string;description:string;theme:WeddingTheme}[] = [
  {id:"garden",name:"Jardim romântico",description:"Delicado, orgânico e acolhedor.",theme:{...defaultTheme}},
  {id:"editorial",name:"Editorial contemporâneo",description:"Tipografia marcante e composição limpa.",theme:{...defaultTheme,template:"editorial",palette:"terracotta",font:"modern",heroAlign:"left"}},
  {id:"classic",name:"Clássico atemporal",description:"Elegante, simétrico e tradicional.",theme:{...defaultTheme,template:"classic",palette:"ocean",font:"classic"}},
];

export const Route = createFileRoute("/_authenticated/painel")({ head: () => ({ meta: [{ title: "Painel do casal — Laço" }, { name: "description", content: "Edite o site, as fotos e acompanhe confirmações." }, { property: "og:title", content: "Painel do casal — Laço" }, { property: "og:description", content: "Área privada de organização do casamento." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Dashboard });

function Dashboard() {
  const { user } = Route.useRouteContext(); const navigate = useNavigate();
  const [wedding,setWedding]=useState<Wedding|null>(null); const [rsvps,setRsvps]=useState<RSVP[]>([]); const [gifts,setGifts]=useState<GiftRow[]>([]); const [giftMessages,setGiftMessages]=useState<GiftMessage[]>([]);
  const [search,setSearch]=useState(""); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(""); const [setupStep,setSetupStep]=useState(1); const [isAdmin,setIsAdmin]=useState(false);
  const [newGift,setNewGift]=useState({name:"",price:"",image_url:""});
  const [manualGuestName,setManualGuestName]=useState("");
  useEffect(()=>{ void load(); },[]);
  async function load(){
    let {data:w}=await supabase.from("weddings").select("*").eq("owner_id",user.id).maybeSingle();
    if(!w){
      const display=String(user.user_metadata?.["full_name"]||user.email?.split("@")[0]||"");
      await supabase.from("profiles").upsert({id:user.id,display_name:display,avatar_url:String(user.user_metadata?.["avatar_url"]||"")||null});
      const created=await supabase.from("weddings").insert({owner_id:user.id,slug:`casamento-${user.id.slice(0,8)}`,couple_names:"Nosso casamento",partner_one_name:"",partner_two_name:"",setup_completed:false}).select().single(); w=created.data;
      if(w) await supabase.from("gifts").insert([{wedding_id:w.id,owner_id:user.id,name:"Lua de mel",price:200},{wedding_id:w.id,owner_id:user.id,name:"Jantar romântico",price:100},{wedding_id:w.id,owner_id:user.id,name:"Jogo de panelas",price:150}]);
    }
    if(!w)return;
    setWedding({...w,ceremony:asVenue(w.ceremony),reception:asVenue(w.reception),pix:asPix(w.pix),theme:asTheme(w.theme)} as unknown as Wedding);
    const [rr,gg,gm,role]=await Promise.all([supabase.from("rsvps").select("*").eq("wedding_id",w.id).order("created_at",{ascending:false}),supabase.from("gifts").select("*").eq("wedding_id",w.id).order("created_at"),supabase.from("gift_messages").select("*").eq("wedding_id",w.id).order("created_at",{ascending:false}),supabase.from("user_roles").select("id").eq("user_id",user.id).eq("role","admin").maybeSingle()]);
    setIsAdmin(Boolean(role.data));
    setRsvps(rr.data||[]); setGifts(gg.data||[]); setGiftMessages(gm.data||[]);
  }
  const set=<K extends keyof Wedding>(key:K,value:Wedding[K])=>wedding&&setWedding({...wedding,[key]:value});
  const setTheme=<K extends keyof WeddingTheme>(key:K,value:WeddingTheme[K])=>wedding&&setWedding({...wedding,theme:{...wedding.theme,[key]:value}});
  async function persist(done=false){ if(!wedding)return false; setSaving(true); setNotice(""); const names=`${wedding.partner_one_name.trim()} & ${wedding.partner_two_name.trim()}`; const payload={couple_names:names,partner_one_name:wedding.partner_one_name.trim(),partner_one_role:wedding.partner_one_role,partner_two_name:wedding.partner_two_name.trim(),partner_two_role:wedding.partner_two_role,wedding_at:wedding.wedding_at,date_text:formatWeddingDate(wedding.wedding_at),cover_photo:wedding.cover_photo,story:wedding.story,whatsapp:wedding.whatsapp,slug:wedding.slug,ceremony:wedding.ceremony as unknown as Json,reception:wedding.reception as unknown as Json,pix:wedding.pix as unknown as Json,theme:wedding.theme as unknown as Json,is_published:wedding.is_published,setup_completed:done||wedding.setup_completed,total_guests:wedding.total_guests}; const {error}=await supabase.from("weddings").update(payload).eq("id",wedding.id); setSaving(false); if(error){setNotice("Não foi possível salvar. Tente novamente.");return false;} setWedding({...wedding,...payload,ceremony:wedding.ceremony,reception:wedding.reception,pix:wedding.pix,theme:wedding.theme} as Wedding);setNotice("Alterações salvas.");return true; }
  async function finishSetup(){ if(!wedding?.partner_one_name.trim()||!wedding.partner_two_name.trim()||!wedding.wedding_at){setNotice("Preencha os dois nomes, os papéis, a data e a hora.");return;} await persist(true); }
  async function addGift(){if(!wedding||!newGift.name||!Number(newGift.price))return;await supabase.from("gifts").insert({wedding_id:wedding.id,owner_id:user.id,name:newGift.name,price:Number(newGift.price),image_url:newGift.image_url||null});setNewGift({name:"",price:"",image_url:""});await load();}
  async function updateGift(g:GiftRow,changes:Partial<GiftRow>){await supabase.from("gifts").update(changes).eq("id",g.id);await load();}
  async function deleteGift(g:GiftRow){if(g.image_url&&!/^https?:\/\//.test(g.image_url))await supabase.storage.from("wedding-photos").remove([g.image_url]);await supabase.from("gifts").delete().eq("id",g.id);await load();}
  async function signOut(){await supabase.auth.signOut();navigate({to:"/auth",replace:true});}
  const stats=useMemo(()=>({yes:rsvps.filter(r=>r.attending).length,no:rsvps.filter(r=>!r.attending).length,people:rsvps.filter(r=>r.attending).reduce((n,r)=>n+1+r.guest_count+r.children_count+r.helpers_count,0)}),[rsvps]);
  const flatConfirmedGuests=useMemo(()=>{
    const list:string[]=[];
    rsvps.filter(r=>r.attending).forEach(r=>{
      if(r.name) list.push(r.name);
      if(r.guest_names) list.push(...r.guest_names);
      if(r.child_names) list.push(...r.child_names);
      if(r.helper_names) list.push(...r.helper_names);
    });
    return list.sort((a,b)=>a.localeCompare(b));
  },[rsvps]);
  const filtered=rsvps.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));
  function exportCsv(){const q=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const rows=[["Nome","Vai?","Qtd. Adultos","Nomes Adultos","Qtd. Crianças","Nomes Crianças","Qtd. Ajuda","Nomes Ajuda","WhatsApp","Recado","Data"],...rsvps.map(r=>[r.name,r.attending?"Sim":"Não",r.guest_count,(r.guest_names||[]).join(", "),r.children_count,(r.child_names||[]).join(", "),r.helpers_count,(r.helper_names||[]).join(", "),r.whatsapp,r.message||"",new Date(r.created_at).toLocaleString("pt-BR")])];const blob=new Blob(["\ufeff"+rows.map(x=>x.map(q).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="confirmacoes.csv";a.click();URL.revokeObjectURL(a.href);}
  async function addManualGuest(){
    if(!wedding||!manualGuestName.trim())return;
    const {error}=await supabase.from("rsvps").insert({
      wedding_id:wedding.id,
      owner_id:user.id,
      name:manualGuestName.trim(),
      attending:true,
      guest_count:0,children_count:0,helpers_count:0,
      whatsapp:"",guest_names:[],child_names:[],helper_names:[]
    });
    if(!error){ setManualGuestName(""); await load(); }
  }
  if(!wedding)return <main className="flex min-h-screen items-center justify-center"><p className="text-muted-foreground">Preparando seu casamento…</p></main>;
  if(!wedding.setup_completed)return <Onboarding wedding={wedding} step={setupStep} setStep={setSetupStep} set={set} finish={finishSetup} saving={saving} notice={notice}/>;
   return <>
     <div className="print:block hidden print:bg-background print:text-foreground print:p-8" style={weddingThemeStyle(wedding.theme)}>
       <div className={`wedding-theme wedding-palette-${wedding.theme.palette} wedding-font-${wedding.theme.font}`}>
         <div className="text-center mb-8">
           <h1 className="text-5xl text-primary font-serif">{wedding.couple_names}</h1>
           <p className="text-lg text-primary/80 mt-2">{formatWeddingDate(wedding.wedding_at)}</p>
           <h2 className="text-2xl mt-8 border-b-2 border-primary/20 pb-4">Lista de Confirmados na Portaria</h2>
         </div>
         <div className="space-y-4">
           {flatConfirmedGuests.map((name, i) => (
             <div key={i} className="flex items-center gap-4 border-b border-border/50 pb-2">
               <div className="w-6 h-6 border-2 border-primary/50 rounded-sm"></div>
               <span className="text-xl font-medium">{name}</span>
             </div>
           ))}
           {flatConfirmedGuests.length === 0 && <p className="text-muted-foreground text-center py-10">Nenhum convidado confirmado ainda.</p>}
         </div>
       </div>
     </div>
     <main className="min-h-screen bg-muted/40 print:hidden"><header className="border-b border-border bg-background"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link to="/" className="font-serif text-3xl text-primary">Laço</Link><div className="flex items-center gap-2">{isAdmin&&<Button variant="outline" asChild><Link to="/admin"><ShieldCheck/> Administração</Link></Button>}<Button variant="outline" asChild><Link to="/casamento/$slug" params={{slug:wedding.slug}} target="_blank"><ExternalLink/> Ver site</Link></Button><Button variant="ghost" size="icon" onClick={signOut} title="Sair"><LogOut/></Button></div></div></header><div className="mx-auto max-w-7xl px-5 py-10"><p className="text-xs font-semibold uppercase text-accent">Painel do casal</p><h1 className="mt-2 text-4xl md:text-5xl">Olá, {wedding.couple_names}</h1><Tabs defaultValue="resumo" className="mt-8"><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-none border-b border-border bg-transparent p-0">{tabs.map(([v,l])=><TabsTrigger key={v} value={v} className="rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-primary data-[state=active]:shadow-none">{l}</TabsTrigger>)}</TabsList>
  <TabsContent value="resumo" className="mt-8"><div className="grid gap-4 md:grid-cols-3">{[[Heart,"Confirmaram",stats.yes],[Users,"Total de pessoas",stats.people],[BarChart3,"Não poderão ir",stats.no]].map(([Icon,label,n])=>{const C=Icon as typeof Heart;return <div className="border border-border bg-background p-6" key={label as string}><C className="text-accent"/><p className="mt-8 text-sm text-muted-foreground">{label as string}</p><strong className="font-serif text-5xl font-normal">{n as number}</strong></div>})}</div><Editor title="Seu endereço"><p className="text-sm text-muted-foreground">Compartilhe este endereço com os convidados.</p><div className="mt-4 flex flex-wrap items-center gap-3"><code className="max-w-full overflow-hidden bg-muted px-3 py-2 text-sm">/casamento/{wedding.slug}</code><Button variant="outline" onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/casamento/${wedding.slug}`)}>Copiar</Button></div></Editor></TabsContent>
   <TabsContent value="site" className="mt-8"><div className="grid gap-8 lg:grid-cols-2"><Editor title="Informações principais"><div className="grid gap-4 sm:grid-cols-2"><PersonField label="Primeira pessoa" wedding={wedding} nameKey="partner_one_name" roleKey="partner_one_role" set={set}/><PersonField label="Segunda pessoa" wedding={wedding} nameKey="partner_two_name" roleKey="partner_two_role" set={set}/></div><Label>Endereço público</Label><Input value={wedding.slug} onChange={e=>set("slug",slugify(e.target.value))}/>
   <div className="grid gap-4 sm:grid-cols-3"><div><Label>Data do casamento</Label><Input className="mt-2" type="date" value={weddingDatePart(wedding.wedding_at)} onChange={e=>set("wedding_at",combineWeddingDateTime(wedding.wedding_at,e.target.value))}/></div><div><Label>Horário do casamento</Label><Input className="mt-2" type="time" value={weddingTimePart(wedding.wedding_at)} onChange={e=>set("wedding_at",combineWeddingDateTime(wedding.wedding_at,undefined,e.target.value))}/></div><div><Label>Total de convidados</Label><Input className="mt-2" type="number" min="0" value={wedding.total_guests} onChange={e=>set("total_guests",parseInt(e.target.value)||0)}/></div></div>
   <PhotoUpload ownerId={user.id} folder="cover" label="Foto principal" value={wedding.cover_photo} onChange={v=>set("cover_photo",v)}/><Label>Nossa história</Label><Textarea className="min-h-32" value={wedding.story} onChange={e=>set("story",e.target.value)}/><Label>WhatsApp</Label><Input value={wedding.whatsapp} onChange={e=>set("whatsapp",e.target.value.replace(/\D/g,""))}/></Editor><div className="space-y-8"><VenueEditor ownerId={user.id} title="Cerimônia" folder="ceremony" value={wedding.ceremony} onChange={v=>set("ceremony",v)}/><VenueEditor ownerId={user.id} title="Recepção" folder="reception" value={wedding.reception} onChange={v=>set("reception",v)}/><Editor title="Pix"><Label>Chave Pix</Label><Input value={wedding.pix.key} onChange={e=>set("pix",{...wedding.pix,key:e.target.value})}/><Label>Nome do recebedor</Label><Input value={wedding.pix.name} onChange={e=>set("pix",{...wedding.pix,name:e.target.value})}/><Label>Cidade</Label><Input value={wedding.pix.city} onChange={e=>set("pix",{...wedding.pix,city:e.target.value})}/></Editor></div></div><SaveBar saving={saving} notice={notice} onSave={()=>void persist()}/></TabsContent>
  <TabsContent value="aparencia" className="mt-8"><div className="grid gap-8 xl:grid-cols-[1fr_.85fr]"><div className="space-y-8"><Editor title="Modelos prontos"><div className="grid gap-3 md:grid-cols-3">{templateOptions.map(option=><TemplateOption key={option.id} option={option} selected={wedding.theme.template===option.id} names={`${wedding.partner_one_name||"Nome"} & ${wedding.partner_two_name||"Nome"}`} onSelect={()=>set("theme",{...option.theme,customColors:wedding.theme.customColors,sections:[...wedding.theme.sections],hidden:[...wedding.theme.hidden]})}/>)}</div></Editor><Editor title="Personalização"><PalettePicker theme={wedding.theme} onChange={theme=>set("theme",theme)}/><ChoiceGrid icon={Type} label="Tipografia" value={wedding.theme.font} options={[["romantic","Romântica"],["modern","Moderna"],["classic","Clássica"]]} onChange={v=>setTheme("font",v as WeddingTheme["font"])}/><ChoiceGrid icon={Sparkles} label="Ícones" value={wedding.theme.icons} options={[["minimal","Minimalistas"],["floral","Florais"],["classic","Clássicos"]]} onChange={v=>setTheme("icons",v as WeddingTheme["icons"])}/><ChoiceGrid icon={LayoutTemplate} label="Alinhamento da abertura" value={wedding.theme.heroAlign} options={[["center","Centralizado"],["left","À esquerda"]]} onChange={v=>setTheme("heroAlign",v as WeddingTheme["heroAlign"])}/></Editor><Editor title="Ordem das seções"><div className="divide-y divide-border">{wedding.theme.sections.map((section,index)=><div key={section} className="flex items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="font-medium">{sectionLabels[section]}</p></div><Switch aria-label={`Exibir ${sectionLabels[section]}`} checked={!wedding.theme.hidden.includes(section)} onCheckedChange={checked=>setTheme("hidden",checked?wedding.theme.hidden.filter(x=>x!==section):[...wedding.theme.hidden,section])}/><Button size="icon" variant="ghost" title="Mover para cima" disabled={index===0} onClick={()=>setTheme("sections",move(wedding.theme.sections,index,-1))}><ArrowUp/></Button><Button size="icon" variant="ghost" title="Mover para baixo" disabled={index===wedding.theme.sections.length-1} onClick={()=>setTheme("sections",move(wedding.theme.sections,index,1))}><ArrowDown/></Button></div>)}</div></Editor></div><div className="xl:sticky xl:top-6 xl:self-start"><p className="mb-3 text-sm font-medium">Prévia ao vivo</p><ThemePreview wedding={wedding}/></div></div><SaveBar saving={saving} notice={notice} onSave={()=>void persist()}/></TabsContent>
  <TabsContent value="presentes" className="mt-8"><Editor title="Lista de presentes"><div className="grid gap-4 lg:grid-cols-3"><div className="space-y-3"><Input placeholder="Nome do presente" value={newGift.name} onChange={e=>setNewGift({...newGift,name:e.target.value})}/><Input placeholder="Valor" type="number" value={newGift.price} onChange={e=>setNewGift({...newGift,price:e.target.value})}/><PhotoUpload ownerId={user.id} folder="gifts" label="Foto do presente" value={newGift.image_url} onChange={image_url=>setNewGift({...newGift,image_url})}/><Button onClick={addGift} className="w-full"><Gift/>Adicionar presente</Button></div><div className="space-y-3 lg:col-span-2">{gifts.map(g=><div key={g.id} className="grid gap-4 border border-border p-4 sm:grid-cols-[1fr_220px_auto] sm:items-center"><div><strong>{g.name}</strong><p className="text-sm text-muted-foreground">R$ {Number(g.price).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div><PhotoUpload ownerId={user.id} folder="gifts" label="Imagem" value={g.image_url||""} onChange={image_url=>void updateGift(g,{image_url:image_url||null})}/><Button size="icon" variant="ghost" title="Excluir presente" onClick={()=>void deleteGift(g)}><Trash2/></Button></div>)}</div></div></Editor></TabsContent>
  <TabsContent value="confirmacoes" className="mt-8"><div className="border border-border bg-background p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-3xl">Confirmações</h2><p className="text-sm text-muted-foreground">{rsvps.length} respostas recebidas</p></div><Button onClick={exportCsv}><Download/>Baixar CSV completo</Button></div><div className="relative mt-6 max-w-sm"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar por nome" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="overflow-x-auto"><Table className="mt-5"><TableHeader><TableRow><TableHead>Nome Principal</TableHead><TableHead>Presença</TableHead><TableHead>Total</TableHead><TableHead>Acompanhantes Adultos</TableHead><TableHead>Crianças</TableHead><TableHead>Ajuda</TableHead><TableHead>WhatsApp</TableHead></TableRow></TableHeader><TableBody>{filtered.map(r=><TableRow key={r.id}><TableCell className="font-medium">{r.name}</TableCell><TableCell>{r.attending?"Sim":"Não"}</TableCell><TableCell>{r.attending?1+r.guest_count+r.children_count+r.helpers_count:0}</TableCell><TableCell className="text-xs">{r.guest_names&&r.guest_names.length>0?r.guest_names.join(", "):"—"}</TableCell><TableCell className="text-xs">{r.child_names&&r.child_names.length>0?r.child_names.join(", "):"—"}</TableCell><TableCell className="text-xs">{r.helper_names&&r.helper_names.length>0?r.helper_names.join(", "):"—"}</TableCell><TableCell>{r.whatsapp||"—"}</TableCell></TableRow>)}</TableBody></Table></div></div></TabsContent>
   <TabsContent value="mural" className="mt-8"><div className="mb-6"><h2 className="text-3xl">Mural de recados</h2><p className="mt-1 text-sm text-muted-foreground">Mensagens deixadas nas confirmações e nos presentes.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rsvps.filter(r=>Boolean(r.message?.trim())).map(r=><MessageCard key={`rsvp-${r.id}`} name={r.name} message={r.message||""} detail={r.attending?"Confirmação de presença":"Aviso de ausência"} date={r.created_at} icon="rsvp"/>)}{giftMessages.map(item=><MessageCard key={`gift-${item.id}`} name={item.sender_name} message={item.message||"Enviou este presente com carinho."} detail={`Presente: ${gifts.find(g=>g.id===item.gift_id)?.name||"Presente escolhido"}`} date={item.created_at} icon="gift"/>)}{!rsvps.some(r=>Boolean(r.message?.trim()))&&giftMessages.length===0&&<div className="border border-dashed border-border bg-background p-10 text-center md:col-span-2 xl:col-span-3"><MessageSquare className="mx-auto size-8 text-muted-foreground"/><p className="mt-3 text-muted-foreground">Os recados dos convidados aparecerão aqui.</p></div>}</div></TabsContent>
  <TabsContent value="acompanhamento" className="mt-8">
    <div className="grid gap-8 lg:grid-cols-[1fr_350px]">
      <div className="space-y-8">
        <Editor title="Acompanhamento de convidados">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-8 border-b border-border pb-8">
            <div className="flex-1">
              <p className="text-sm font-medium text-muted-foreground mb-2">Progresso da lista</p>
              <div className="flex items-baseline gap-2">
                <span className="text-5xl font-serif text-primary">{stats.people}</span>
                <span className="text-2xl text-muted-foreground">/ {wedding.total_guests || 0} confirmados</span>
              </div>
              <div className="h-4 bg-secondary mt-4 overflow-hidden">
                <div className="h-full bg-primary transition-all" style={{ width: `${Math.min(100, wedding.total_guests > 0 ? (stats.people / wedding.total_guests) * 100 : 0)}%` }}></div>
              </div>
            </div>
          </div>
          
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-medium text-lg">Lista plana de confirmados</h3>
            <Button variant="outline" onClick={() => window.print()}><Printer className="mr-2 h-4 w-4"/>Imprimir Portaria</Button>
          </div>
          
          <div className="border border-border rounded-md overflow-hidden max-h-[600px] overflow-y-auto bg-muted/20">
            <div className="divide-y divide-border/50">
              {flatConfirmedGuests.map((name, i) => (
                <div key={i} className="flex items-center gap-3 p-3 hover:bg-muted/50 transition-colors">
                  <div className="w-5 h-5 border border-primary/50 rounded-sm bg-background"></div>
                  <span className="font-medium">{name}</span>
                </div>
              ))}
              {flatConfirmedGuests.length === 0 && <p className="p-8 text-center text-muted-foreground">Nenhum convidado confirmado.</p>}
            </div>
          </div>
        </Editor>
      </div>
      <div>
        <Editor title="Adicionar manualmente">
          <p className="text-sm text-muted-foreground mb-4">
            Alguém confirmou pelo WhatsApp? Adicione o nome aqui para ir direto para a lista.
          </p>
          <div className="space-y-3">
            <Input 
              placeholder="Nome do convidado" 
              value={manualGuestName} 
              onChange={e => setManualGuestName(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && addManualGuest()}
            />
            <Button onClick={addManualGuest} className="w-full" disabled={!manualGuestName.trim()}>
              Adicionar confirmado
            </Button>
          </div>
        </Editor>
      </div>
    </div>
  </TabsContent>
  </Tabs></div></main></>;
}

function Onboarding({wedding,step,setStep,set,finish,saving,notice}:{wedding:Wedding;step:number;setStep:(n:number)=>void;set:<K extends keyof Wedding>(key:K,value:Wedding[K])=>void;finish:()=>void;saving:boolean;notice:string}){return <main className="min-h-screen bg-secondary/40 px-5 py-10"><div className="mx-auto max-w-2xl"><p className="font-serif text-3xl text-primary">Laço</p><div className="mt-10 flex gap-2">{[1,2].map(n=><div key={n} className={`h-1 flex-1 ${n<=step?"bg-primary":"bg-border"}`}/>)}</div><div className="mt-8 bg-background p-6 shadow-xl md:p-10">{step===1?<><p className="text-xs font-semibold uppercase text-accent">Primeiro passo</p><h1 className="mt-2 text-4xl">Quem vai se casar?</h1><p className="mt-3 text-muted-foreground">Essas informações já deixam o site pronto para vocês.</p><div className="mt-8 grid gap-6 sm:grid-cols-2"><PersonField label="Primeira pessoa" wedding={wedding} nameKey="partner_one_name" roleKey="partner_one_role" set={set}/><PersonField label="Segunda pessoa" wedding={wedding} nameKey="partner_two_name" roleKey="partner_two_role" set={set}/></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div><Label>Data do casamento</Label><Input className="mt-2 h-11" type="date" value={weddingDatePart(wedding.wedding_at)} onChange={e=>set("wedding_at",combineWeddingDateTime(wedding.wedding_at,e.target.value))}/></div><div><Label>Horário do casamento</Label><Input className="mt-2 h-11" type="time" value={weddingTimePart(wedding.wedding_at)} onChange={e=>set("wedding_at",combineWeddingDateTime(wedding.wedding_at,undefined,e.target.value))}/></div></div><Button className="mt-8 w-full" size="lg" onClick={()=>setStep(2)}>Continuar</Button></>:<><p className="text-xs font-semibold uppercase text-accent">Último passo</p><h1 className="mt-2 text-4xl">Onde será?</h1><p className="mt-3 text-muted-foreground">Preencha o que já souber. Os locais podem ficar para depois.</p><div className="mt-8 grid gap-6 sm:grid-cols-2"><SimpleVenue title="Cerimônia" value={wedding.ceremony} onChange={v=>set("ceremony",v)}/><SimpleVenue title="Recepção" value={wedding.reception} onChange={v=>set("reception",v)}/></div>{notice&&<p className="mt-5 text-sm text-destructive">{notice}</p>}<div className="mt-8 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><Button variant="ghost" onClick={()=>setStep(1)}>Voltar</Button><div className="flex flex-col gap-3 sm:flex-row"><Button variant="outline" onClick={finish} disabled={saving}>Responder locais depois</Button><Button onClick={finish} disabled={saving}>{saving?"Criando…":"Criar meu site"}<Check/></Button></div></div></>}</div></div></main>}
function PersonField({label,wedding,nameKey,roleKey,set}:{label:string;wedding:Wedding;nameKey:"partner_one_name"|"partner_two_name";roleKey:"partner_one_role"|"partner_two_role";set:<K extends keyof Wedding>(key:K,value:Wedding[K])=>void}){return <div className="space-y-2"><Label>{label}</Label><Input placeholder="Nome" value={wedding[nameKey]} onChange={e=>set(nameKey,e.target.value)}/><Select value={wedding[roleKey]} onValueChange={v=>set(roleKey,v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="noiva">Noiva</SelectItem><SelectItem value="noivo">Noivo</SelectItem></SelectContent></Select></div>}
function SimpleVenue({title,value,onChange}:{title:string;value:Venue;onChange:(v:Venue)=>void}){return <div className="space-y-3"><h2 className="text-2xl">{title}</h2><Input placeholder="Nome do local" value={value.local} onChange={e=>onChange({...value,local:e.target.value})}/><Input placeholder="Endereço" value={value.endereco} onChange={e=>onChange({...value,endereco:e.target.value})}/><Input type="url" placeholder="Link do local no Google Maps" value={value.maps_url} onChange={e=>onChange({...value,maps_url:e.target.value})}/></div>}
function Editor({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-8 border border-border bg-background p-6 first:mt-0"><h2 className="mb-6 text-3xl">{title}</h2><div className="space-y-4">{children}</div></section>}
function VenueEditor({ownerId,title,folder,value,onChange}:{ownerId:string;title:string;folder:string;value:Venue;onChange:(v:Venue)=>void}){return <Editor title={title}><Label>Nome do local</Label><Input value={value.local} onChange={e=>onChange({...value,local:e.target.value})}/><div className="grid gap-4 sm:grid-cols-2"><div><Label>Data</Label><Input className="mt-2" type="date" value={value.data} onChange={e=>onChange({...value,data:e.target.value})}/></div><div><Label>Horário</Label><Input className="mt-2" type="time" value={value.hora} onChange={e=>onChange({...value,hora:e.target.value})}/></div></div><Label>Endereço</Label><Input value={value.endereco} onChange={e=>onChange({...value,endereco:e.target.value})}/><Label>Link do local no Google Maps</Label><Input type="url" placeholder="https://maps.app.goo.gl/..." value={value.maps_url} onChange={e=>onChange({...value,maps_url:e.target.value})}/><div className="grid gap-4 sm:grid-cols-2">{value.fotos.map((photo,index)=><PhotoUpload key={`${photo}-${index}`} ownerId={ownerId} folder={folder} label={`Foto ${index+1}`} value={photo} onChange={next=>onChange({...value,fotos:value.fotos.map((item,i)=>i===index?next:item).filter(Boolean)})}/>)}</div><PhotoUpload ownerId={ownerId} folder={folder} label="Adicionar foto" value="" onChange={photo=>onChange({...value,fotos:[...value.fotos,photo]})}/></Editor>}
function TemplateOption({option,selected,names,onSelect}:{option:(typeof templateOptions)[number];selected:boolean;names:string;onSelect:()=>void}){return <Button type="button" variant="outline" onClick={onSelect} className={`h-auto min-w-0 flex-col items-stretch overflow-hidden p-0 text-left ${selected?"border-primary ring-2 ring-primary/20":""}`}><div className={`wedding-theme wedding-palette-${option.theme.palette} wedding-font-${option.theme.font} w-full bg-background text-foreground`}><div className={`flex aspect-[5/3] flex-col justify-end bg-primary p-4 text-primary-foreground ${option.theme.heroAlign==="center"?"items-center text-center":"items-start"}`}><span className="text-[8px] uppercase">Nós vamos nos casar</span><strong className="mt-1 font-normal text-lg leading-none">{names}</strong><span className="mt-2 text-[8px]">15 · NOV · 2026</span></div><div className={`grid gap-1.5 p-3 ${option.id==="editorial"?"grid-cols-[.7fr_1.3fr]":option.id==="classic"?"text-center":"grid-cols-2"}`}><div className="h-1.5 bg-accent"/><div className="h-1.5 bg-secondary"/><div className="h-1.5 bg-secondary"/><div className="h-1.5 bg-accent/60"/></div></div><div className="w-full p-4"><strong className="block">{option.name}</strong><span className="mt-1 block whitespace-normal text-xs text-muted-foreground">{option.description}</span></div></Button>}
function PalettePicker({theme,onChange}:{theme:WeddingTheme;onChange:(theme:WeddingTheme)=>void}){const palettes:[[WeddingTheme["palette"],string,string[]]]|[WeddingTheme["palette"],string,string[]][]=[["olive","Verde oliva",["#365b45","#b87858","#fbf8f1"]],["rose","Rosa antigo",["#8a4c52","#c66f6a","#fbf3f2"]],["ocean","Azul sereno",["#346878","#4fa08c","#f2fbfa"]],["terracotta","Terracota",["#945137","#c17445","#fbf7ed"]]];const setColor=(key:keyof WeddingTheme["customColors"],value:string)=>onChange({...theme,palette:"custom",customColors:{...theme.customColors,[key]:value}});return <div><p className="mb-3 flex items-center gap-2 text-sm font-medium"><Palette className="size-4"/>Cores</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{palettes.map(([id,name,colors])=><Button key={id} type="button" variant="outline" onClick={()=>onChange({...theme,palette:id})} className={`h-auto flex-col items-start gap-2 p-3 ${theme.palette===id?"border-primary ring-2 ring-primary/20":""}`}><span className="flex w-full overflow-hidden rounded-sm">{colors.map(color=><span key={color} className="h-5 flex-1" style={{backgroundColor:color}}/>)}</span><span className="text-xs">{name}</span></Button>)}</div><div className={`mt-3 border p-4 ${theme.palette==="custom"?"border-primary bg-secondary/40":"border-border"}`}><div className="mb-4 flex items-center justify-between gap-3"><div><p className="font-medium">Paleta personalizada</p><p className="text-xs text-muted-foreground">Escolha qualquer tom no espectro completo.</p></div>{theme.palette!=="custom"&&<Button type="button" variant="outline" size="sm" onClick={()=>onChange({...theme,palette:"custom"})}>Usar</Button>}</div><div className="grid gap-3 sm:grid-cols-3"><ColorField label="Principal" value={theme.customColors.primary} onChange={value=>setColor("primary",value)}/><ColorField label="Destaque" value={theme.customColors.accent} onChange={value=>setColor("accent",value)}/><ColorField label="Fundo" value={theme.customColors.background} onChange={value=>setColor("background",value)}/></div></div></div>}
function ColorField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="text-xs font-medium"><span className="mb-2 block">{label}</span><span className="flex items-center gap-2 border border-input bg-background p-2"><input type="color" aria-label={`Escolher cor ${label.toLowerCase()}`} value={value} onChange={event=>onChange(event.target.value)} className="h-9 w-11 cursor-pointer border-0 bg-transparent p-0"/><span className="font-mono text-[11px] uppercase text-muted-foreground">{value}</span></span></label>}
function ChoiceGrid({icon:Icon,label,value,options,onChange}:{icon:typeof Palette;label:string;value:string;options:string[][];onChange:(v:string)=>void}){return <div><p className="mb-3 flex items-center gap-2 text-sm font-medium"><Icon className="size-4"/>{label}</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{options.map(([id,name])=><Button type="button" key={id??name} variant={value===id?"default":"outline"} onClick={()=>id&&onChange(id)}>{name}</Button>)}</div></div>}
function move(items:WeddingSection[],index:number,offset:number){const copy=[...items];const target=index+offset;const current=copy[index];const replacement=copy[target];if(!current||!replacement)return copy;copy[index]=replacement;copy[target]=current;return copy}
function ThemePreview({wedding}:{wedding:Wedding}){return <div style={weddingThemeStyle(wedding.theme)} className={`wedding-theme wedding-palette-${wedding.theme.palette} wedding-font-${wedding.theme.font} overflow-hidden border border-border bg-background shadow-xl`}><div className={`flex aspect-[4/3] flex-col justify-end bg-primary p-8 text-primary-foreground ${wedding.theme.heroAlign==="center"?"items-center text-center":"items-start text-left"}`}><span className="text-xs uppercase">Nós vamos nos casar</span><h2 className="mt-3 text-5xl leading-none">{wedding.partner_one_name||"Nome"} & {wedding.partner_two_name||"Nome"}</h2><p className="mt-4 text-sm">{formatWeddingDate(wedding.wedding_at)}</p></div><div className="space-y-3 p-5">{wedding.theme.sections.filter(x=>!wedding.theme.hidden.includes(x)).map(section=><div key={section} className="border-b border-border pb-3 text-sm">{sectionLabels[section]}</div>)}</div></div>}
function SaveBar({saving,notice,onSave}:{saving:boolean;notice:string;onSave:()=>void}){return <div className="mt-6 flex flex-wrap items-center gap-4"><Button size="lg" onClick={onSave} disabled={saving}><Save/>{saving?"Salvando…":"Salvar alterações"}</Button>{notice&&<p className="text-sm text-muted-foreground">{notice}</p>}</div>}
function MessageCard({name,message,detail,date,icon}:{name:string;message:string;detail:string;date:string;icon:"rsvp"|"gift"}){const Icon=icon==="gift"?Gift:Heart;return <article className="flex min-h-56 flex-col border border-border bg-background p-6"><div className="flex items-center justify-between gap-4"><span className="flex size-10 items-center justify-center rounded-full bg-secondary text-primary"><Icon className="size-5"/></span><time className="text-xs text-muted-foreground">{new Date(date).toLocaleDateString("pt-BR")}</time></div><blockquote className="mt-6 flex-1 text-lg leading-7">“{message}”</blockquote><div className="mt-6 border-t border-border pt-4"><p className="font-medium">{name}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div></article>}